const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const cp = require('node:child_process');
const root = '/tmp/raine-proxy-audit-iNNtqV';
const source = path.join(root, 'raine-claude-code-proxy-bcfa0a4');
const sha = 'bcfa0a401a6bfe0eea278c65edecfcedaad919c4';
const read = p => fs.readFileSync(path.join(source, p), 'utf8');
const hash = b => crypto.createHash('sha256').update(b).digest('hex');
const urls = [...fs.readFileSync(path.join(root, 'sitemap.xml'),'utf8').matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);
const opencode = [...read('src/providers/opencode/model.rs').split('pub fn resolve')[0].matchAll(/id: "([^"]+)",\s+endpoint: EndpointKind::(\w+)/g)].map(m=>({provider:'opencode-go',model:m[1],protocol:m[2]}));
const registry = read('src/registry.rs');
const arr = name => [...registry.match(new RegExp(name+':[^=]*= &\\[([\\s\\S]*?)\\];'))[1].matchAll(/"([^"]+)"/g)].map(m=>m[1]);
const catalog = {source_sha:sha,opencode,codex:arr('CODEX_MODELS'),kimi_aliases:arr('KIMI_MODELS'),grok:arr('GROK_MODELS'),cursor_prefixes:arr('CURSOR_PREFIXES'),cursor_legacy:arr('CURSOR_LEGACY_MODELS'),cursor_dynamic:'NOT_QUERIED: no account login',account_entitlements:'NOT_TESTED'};
fs.writeFileSync(path.join(__dirname,'model-catalog.json'),JSON.stringify(catalog,null,2)+'\n');
const documents=urls.map(url=>{const route=new URL(url).pathname;const local=route==='/'?'docs/src/content/docs/index.md':`docs/src/content/docs${route.replace(/\/$/,'')}.md`;
 const candidates=[local,local.replace(/\.md$/,'.mdx'),route==='/reference/changelog/'?'CHANGELOG.md':''];
 const found=candidates.find(p=>p&&fs.existsSync(path.join(source,p)));
 return {url,source:found??'UNMAPPED',sha256:found?hash(read(found)):null,review:'assembled documentation body read'};
});
const sourceFiles=['src/registry.rs','src/provider.rs','src/server.rs','src/providers/codex/auth/constants.rs','src/providers/codex/auth/pkce.rs','src/providers/codex/client.rs','src/providers/codex/mod.rs','src/providers/codex/translate/model_allowlist.rs','src/providers/opencode/model.rs','src/providers/kimi/translate/model_allowlist.rs','src/providers/cursor/model.rs','LICENSE'];
const manifest={source_sha:sha,documents,assembled_body:{file:'llms.txt',bytes:fs.statSync(path.join(root,'llms.txt')).size,sha256:hash(fs.readFileSync(path.join(root,'llms.txt')))},source_files:sourceFiles.map(p=>({path:p,sha256:hash(read(p))}))};
fs.writeFileSync(path.join(__dirname,'corpus-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
const result={sitemap_pages:urls.length,mapped_pages:documents.filter(d=>d.source!=='UNMAPPED').length,codex_base_models:catalog.codex.length,kimi_public_ids:catalog.kimi_aliases.length,grok_models:catalog.grok.length,opencode_models:opencode.length,opencode_protocols:Object.fromEntries(['ChatCompletions','Messages','Responses'].map(p=>[p,opencode.filter(m=>m.protocol===p).length]))};
console.log(JSON.stringify(result));
if(documents.some(d=>d.source==='UNMAPPED')) console.log(documents.filter(d=>d.source==='UNMAPPED'));
fs.writeFileSync(path.join(__dirname,'inventory-output.json'),JSON.stringify(result,null,2)+'\n');
