#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# MoAI IGGDA Phase Driver Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the standalone iggda-phase-driver.sh.
# The driver reads progress.md + invokes moai spec audit --filter-spec, then
# emits exit codes + JSON. It MUST NOT invoke AskUserQuestion (the asymmetric
# orchestrator-subagent boundary).
# Project-local hook: .claude/hooks/moai/iggda-phase-driver.sh

# Single-level rotation at 10MB (best-effort, non-blocking)
if [ -f "$MOAI_HOOK_STDERR_LOG" ]; then
    hook_log_size=$(stat -f%z "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || stat -c%s "$MOAI_HOOK_STDERR_LOG" 2>/dev/null || echo 0)
    if [ "$hook_log_size" -gt 10485760 ]; then
        mv -f "$MOAI_HOOK_STDERR_LOG" "${MOAI_HOOK_STDERR_LOG}.1" 2>/dev/null || true
    fi
fi

# Invoke the standalone IGGDA phase driver (sibling script in the same dir).
# Path is inlined (not via a shell var) to satisfy the template unexpanded-token
# check — only $CLAUDE_PROJECT_DIR / $HOME / $MOAI_HOOK_STDERR_LOG are passthrough.
if [ -f "$CLAUDE_PROJECT_DIR/.claude/hooks/moai/iggda-phase-driver.sh" ]; then
    exec bash "$CLAUDE_PROJECT_DIR/.claude/hooks/moai/iggda-phase-driver.sh" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Driver absent — exit silently (Claude Code handles missing hooks gracefully).
exit 0
