#!/bin/bash

MOAI_HOOK_STDERR_LOG="${MOAI_HOOK_STDERR_LOG:-$HOME/.moai/logs/hook-stderr.log}"
mkdir -p "$(dirname "$MOAI_HOOK_STDERR_LOG")" 2>/dev/null || true
# MoAI SessionEnd Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook session-end command.
# Project-local hook: .claude/hooks/moai/session-end.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file (64KB limit)
head -c 65536 > "$temp_file"
if [ $(stat -f%z "$temp_file" 2>/dev/null || stat -c%s "$temp_file" 2>/dev/null || wc -c < "$temp_file") -ge 65536 ]; then
    echo '{"decision":"block","reason":"stdin exceeds 64KB limit"}'
    exit 0
fi

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook session-end < "$temp_file" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
	exec "$HOME/go/bin/moai" hook session-end < "$temp_file" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
	exec "$HOME/.local/bin/moai" hook session-end < "$temp_file" 2>>"$MOAI_HOOK_STDERR_LOG"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
