# Dependabot Configuration for MoAI-ADK
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "modu-ai/moai-adk-maintainers"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security updates always separate
    ignore:
      # Ignore specific packages if needed
      # - dependency-name: "package-name"
      #   versions: ["1.x", "2.x"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "modu-ai/moai-adk-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

# Note: npm ecosystem intentionally excluded
# MoAI-ADK is a pure Python project (hatchling build system)
# npm dependencies were removed in v0.2.15
