# @DOC:DOCS-SYSTEM-001 | SPEC: .moai/specs/SPEC-DOCS-SYSTEM-001/spec.md
# MkDocs Material Configuration for MoAI-ADK v0.3.0

site_name: MoAI-ADK
site_description: MoAI Agentic Development Kit - SPEC-First TDD Framework with Alfred SuperAgent
site_url: https://moai-adk.vercel.app
repo_url: https://github.com/modu-ai/moai-adk
repo_name: modu-ai/moai-adk
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 MoAI Team

# Theme Configuration
theme:
  name: material
  language: ko
  palette:
    # Light mode (Notion-style: 베이지/크림 배경)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode (Notion-style: 다크 그레이)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Noto Sans KR
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      lang:
        - ko
        - en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            members_order: source

# Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Your First Project: getting-started/first-project.md

  - Guides:
    - SPEC-First TDD: guides/spec-first-tdd.md
    - Alfred SuperAgent: guides/alfred-superagent.md
    - 3-Stage Workflow: guides/workflow.md
    - TAG System: guides/tag-system.md
    - TRUST Principles: guides/trust-principles.md

  - Agents:
    - trust-checker: agents/trust-checker.md
    - cc-manager: agents/cc-manager.md
    - project-manager: agents/project-manager.md

  - API Reference:
    - Core: api/core.md
    - CLI: api/cli.md
    - Templates: api/templates.md

  - SPEC Documents:
    - Overview: specs/overview.md
    - Metadata Standard: specs/metadata.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/modu-ai/moai-adk
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/moai-adk/

# Extra CSS
extra_css:
  - stylesheets/extra.css
