package embedemit

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestRenderDeterministic pins byte-stability: the same path set renders to
// the same bytes, so the committed manifest never churns between runs.
func TestRenderDeterministic(t *testing.T) {
	paths := []string{"templates/b.md", "templates/.claude/a.md", "templates/a.md"}
	first, err := Render(paths)
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	second, err := Render(paths)
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("Render() is not deterministic: two runs over the same paths differ")
	}
}

// TestRenderShape pins the structural contract of the emitted file: header,
// package clause, the fixed catalog.yaml directive, one sorted directive per
// approved path, and the embeddedRaw declaration.
func TestRenderShape(t *testing.T) {
	paths := []string{"templates/z.md", "templates/.claude/a.md", "templates/a.md"}
	raw, err := Render(paths)
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	s := string(raw)
	if !strings.Contains(s, "Code generated by internal/template/embedemit; DO NOT EDIT.") {
		t.Error("rendered file lacks the generated-code header")
	}
	if !strings.Contains(s, "package template\n") {
		t.Error("rendered file lacks the package clause")
	}
	directives, err := ParseDirectives(raw)
	if err != nil {
		t.Fatalf("ParseDirectives() error: %v", err)
	}
	// catalog.yaml first, then the approved paths sorted.
	wantDirectives := []string{"catalog.yaml", "templates/.claude/a.md", "templates/a.md", "templates/z.md"}
	if len(directives) != len(wantDirectives) {
		t.Fatalf("ParseDirectives() = %d directives, want %d", len(directives), len(wantDirectives))
	}
	for i, d := range directives {
		if d != wantDirectives[i] {
			t.Errorf("directive[%d] = %q, want %q", i, d, wantDirectives[i])
		}
	}
	if !strings.Contains(s, "var embeddedRaw embed.FS\n") {
		t.Error("rendered file lacks the embeddedRaw declaration")
	}
	if !sort.StringsAreSorted(directives[1:]) {
		t.Error("templates/ directives are not sorted after catalog.yaml")
	}
}

// TestRenderRejectsInvalidPatterns pins the generator-contract validation:
// only single clean slash-separated paths under templates/ render.
func TestRenderRejectsInvalidPatterns(t *testing.T) {
	cases := map[string]string{
		"parent directory": "templates/../escape.md",
		"backslash":        `templates\.claude\a.md`,
		"absolute path":    "/etc/passwd",
		"empty":            "",
		"space":            "templates/my file.md",
		"outside prefix":   "cmd/moai/main.go",
		// go:embed reads [c] as a character class and {a,b} as alternation,
		// so a bracketed tracked name would drop from the embed set while an
		// untracked name matching the class could be pulled in (card t1539
		// review): the emitter refuses glob metacharacters instead.
		"character class": "templates/a[x].md",
		"alternation":     "templates/{a,b}.md",
	}
	for name, p := range cases {
		if _, err := Render([]string{p}); err == nil {
			t.Errorf("%s: Render(%q) accepted an invalid pattern", name, p)
		}
	}
}

// TestApprovedPathsSortsAndDeduplicates feeds an unsorted list with a
// duplicate through Render and pins the normalized output.
func TestApprovedPathsSortsAndDeduplicates(t *testing.T) {
	raw, err := Render([]string{"templates/b.md", "templates/a.md", "templates/b.md"})
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	directives, err := ParseDirectives(raw)
	if err != nil {
		t.Fatalf("ParseDirectives() error: %v", err)
	}
	if got := len(directives); got != 3 { // catalog.yaml + 2 unique paths
		t.Fatalf("got %d directives, want 3 (catalog.yaml + 2 deduplicated paths)", got)
	}
}

// TestGoldenCommittedArtifactsMatchEmission is the regeneration gate, in the
// same shape as the agents-emit golden: run with EMBED_MANIFEST_UPDATE=1 to
// rewrite internal/template/embed_manifest_gen.go (the `make embed-manifest`
// verb); run bare it judges the committed manifest against a fresh emission
// from the tracked template file set (the `make embed-manifest-check`
// target). It never writes in check mode.
func TestGoldenCommittedArtifactsMatchEmission(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	paths, err := ApprovedPaths(repoRoot)
	if err != nil {
		t.Fatalf("ApprovedPaths() error: %v", err)
	}
	if len(paths) == 0 {
		t.Fatal("ApprovedPaths() returned 0 entries — the tracked template set is empty or git ls-files failed silently")
	}
	rendered, err := Render(paths)
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	manifestPath := filepath.Join("..", "embed_manifest_gen.go")
	if os.Getenv("EMBED_MANIFEST_UPDATE") != "" {
		if err := os.WriteFile(manifestPath, rendered, 0o644); err != nil {
			t.Fatalf("write embed manifest: %v", err)
		}
		committed, err := os.ReadFile(manifestPath)
		if err != nil {
			t.Fatalf("re-read written manifest: %v", err)
		}
		if !bytes.Equal(committed, rendered) {
			t.Fatal("written manifest differs from the emission — the generator is not deterministic")
		}
		t.Logf("embed manifest updated: %d approved paths", len(paths))
		return
	}
	committed, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatalf("embed manifest %s is unreadable (%v) — run `make embed-manifest` to emit it", manifestPath, err)
	}
	if !bytes.Equal(committed, rendered) {
		t.Fatalf("embed manifest drift: committed %s differs from a fresh emission (%d committed bytes vs %d emitted) — run `make embed-manifest`", manifestPath, len(committed), len(rendered))
	}
}

// TestTemplatesDiskMatchesManifest judges the on-disk templates/ tree
// against the committed manifest — the build-gate half of the boundary:
// an ignored or untracked file dropped into templates/ is an unapproved
// extra here, and a tracked-but-unregenerated change is a stale entry.
func TestTemplatesDiskMatchesManifest(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "embed_manifest_gen.go"))
	if err != nil {
		t.Fatalf("embed manifest is unreadable (%v) — run `make embed-manifest` to emit it", err)
	}
	directives, err := ParseDirectives(raw)
	if err != nil {
		t.Fatalf("ParseDirectives() error: %v", err)
	}
	want := make(map[string]struct{})
	for _, d := range directives {
		if !strings.HasPrefix(d, "templates/") {
			continue
		}
		want[strings.TrimPrefix(d, "templates/")] = struct{}{}
	}
	if len(want) == 0 {
		t.Fatal("manifest carries 0 templates/ entries — the allowlist boundary is absent")
	}
	var got []string
	walkErr := filepath.WalkDir(filepath.Join("..", "templates"), func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel := strings.TrimPrefix(filepath.ToSlash(p), "../templates/")
		got = append(got, rel)
		return nil
	})
	if walkErr != nil {
		t.Fatalf("walk templates/: %v", walkErr)
	}
	sort.Strings(got)
	gotSet := make(map[string]struct{}, len(got))
	for _, p := range got {
		gotSet[p] = struct{}{}
	}
	var extra, missing []string
	for _, p := range got {
		if _, ok := want[p]; !ok {
			extra = append(extra, p)
		}
	}
	for p := range want {
		if _, ok := gotSet[p]; !ok {
			missing = append(missing, p)
		}
	}
	const maxShow = 20
	if len(extra) > 0 {
		if len(extra) > maxShow {
			extra = extra[:maxShow]
		}
		t.Errorf("%d on-disk template file(s) are not approved by the embed manifest (showing up to %d): %v", len(extra), maxShow, extra)
	}
	if len(missing) > 0 {
		if len(missing) > maxShow {
			missing = missing[:maxShow]
		}
		t.Errorf("%d manifest path(s) approved but absent from disk (showing up to %d): %v", len(missing), maxShow, missing)
	}
}
