name: ci
on: [push]
jobs:
  Test:
    name: "Test (${{ matrix.a.x }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [{x: ubuntu}]
        b: [{y: win}]
        exclude:
          - b:
              y: win
    steps:
      - run: "true"
