name: ci
on: [push]
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - run: "true"
