import fs from 'node:fs';
import cp from 'node:child_process';
import path from 'node:path';
import crypto from 'node:crypto';
const root='/Users/goos/MoAI/moai-adk-go', out='/tmp/moai-workflow-audit.ZD4KBb';
const results=[];
function run(command,args,opts={}) {const r=cp.spawnSync(command,args,{encoding:'utf8',timeout:30000,...opts});return {exit:r.status,stdout:r.stdout?.trim()||'',stderr:r.stderr?.trim()||'',error:r.error?.message};}
const git=(dir,...args)=>run('git',['-C',dir,...args]);
const fixture=out+'/fixture';fs.mkdirSync(fixture,{recursive:true});git(fixture,'init','-q');git(fixture,'config','user.name','Audit fixture');git(fixture,'config','user.email','audit@example.invalid');
fs.writeFileSync(fixture+'/base.txt','base\n');git(fixture,'add','base.txt');git(fixture,'-c','core.hooksPath=/dev/null','commit','-qm','fixture baseline');
const key=()=>{const h=crypto.createHash('sha256');h.update(git(fixture,'status','--porcelain=v2').stdout+'\n');h.update(Buffer.from([0]));h.update(git(fixture,'diff','HEAD').stdout);return h.digest('hex');};
fs.writeFileSync(fixture+'/new.go','package demo\n// version A\n');const p1=git(fixture,'status','--porcelain=v2'),d1=git(fixture,'diff','HEAD'),k1=key();fs.writeFileSync(fixture+'/new.go','package demo\n// version B with changed behavior\n');const p2=git(fixture,'status','--porcelain=v2'),d2=git(fixture,'diff','HEAD'),k2=key();
results.push({id:'P01',command:'git status --porcelain=v2; git diff HEAD — untracked new.go content A → B in isolated fixture',output:`porcelain_before=${p1.stdout}\nporcelain_after=${p2.stdout}\ndiff_before=${JSON.stringify(d1.stdout)}\ndiff_after=${JSON.stringify(d2.stdout)}\nkey_inputs_equal=${p1.stdout===p2.stdout&&d1.stdout===d2.stdout}\ncomputed_digest_equal=${k1===k2}`,meaning:'Key 함수의 세 입력 중 HEAD 고정, 나머지 두 입력 동일. 실제 Key 함수 직접 호출은 별도 소스 추출 probe에서 확인.'});
results.push({id:'P02',command:'bash -c: which() { return 0; }; golangci-lint() { return 7; }; which golangci-lint && golangci-lint run --timeout=5m || echo "SKIP: golangci-lint not installed"',...run('bash',['-c','which() { return 0; }; golangci-lint() { return 7; }; which golangci-lint && golangci-lint run --timeout=5m || echo "SKIP: golangci-lint not installed"'])});
results.push({id:'P03',command:'bash -c: (exit 7) & (exit 0) & wait; printf "wait_status=%s" "$?"',...run('bash',['-c','(exit 7) & (exit 0) & wait; printf "wait_status=%s" "$?"'])});
const hook=root+'/.claude/hooks/moai/sync-phase-quality-gate.sh';
const bin=out+'/bin';fs.mkdirSync(bin,{recursive:true});fs.writeFileSync(bin+'/go','#!/bin/sh\nprintf "%s\\n" "$*" >> "$PROBE_LOG"\nexit 7\n',{mode:0o755});
fs.writeFileSync(fixture+'/go.mod','module fixture\ngo 1.26\n');git(fixture,'add','go.mod','new.go');git(fixture,'-c','core.hooksPath=/dev/null','commit','-qm','docs(SPEC-PROBE-001): sync-phase artifacts');
const env={...process.env,PATH:bin+':'+process.env.PATH,CLAUDE_PROJECT_DIR:fixture,MOAI_SYNC_GATE_BLOCKING:'1',MOAI_AUTONOMY_TIER:'semi-autonomous',PROBE_LOG:out+'/hook-tools.log'};
const first=run('bash',[hook],{cwd:fixture,env,input:'{}'}),second=run('bash',[hook],{cwd:fixture,env,input:'{}'});
results.push({id:'P04',command:'bash <source>/sync-phase-quality-gate.sh, twice at identical fixture HEAD; fake go exits 7',output:JSON.stringify({first,second,tool_calls:fs.readFileSync(out+'/hook-tools.log','utf8').trim().split('\n')},null,2)});
const kotlin=out+'/kotlin';fs.mkdirSync(kotlin,{recursive:true});fs.writeFileSync(kotlin+'/build.gradle.kts','plugins { kotlin("jvm") version "fixture" }\n');
results.push({id:'P05',command:'source sync-phase-quality-gate.sh; detect_language <fixture with build.gradle.kts>',...run('bash',['-c','source "$1"; detect_language "$2"','probe',hook,kotlin])});
const normSource=fs.readFileSync(root+'/internal/runtime/audit_cache.go','utf8').match(/func normalizeWhitespace\(s string\) string \{[\s\S]*?\n\}/)[0];
fs.writeFileSync(out+'/normalize.go',`package main\nimport("fmt";"strings")\n${normSource}\nfunc main(){a:="command: |\\n  echo first\\n  echo second\\n";b:="command: |\\n  echo first echo second\\n";fmt.Printf("different_source=%t\\nnormalized_equal=%t\\nnormalized=%q\\n",a!=b,normalizeWhitespace(a)==normalizeWhitespace(b),normalizeWhitespace(a))}\n`);
results.push({id:'P06',command:'go run normalize.go — normalizeWhitespace function extracted verbatim from internal/runtime/audit_cache.go',...run('go',['run',out+'/normalize.go'])});
const keySource=fs.readFileSync(root+'/internal/verify/key.go','utf8').replace('package verify','package main').replace('"github.com/modu-ai/moai-adk/internal/execerr"','"os"').replace('execerr.StatusDetail(err)','err.Error()');
fs.writeFileSync(out+'/key.go',keySource+`\nfunc main(){dir:=os.Args[1];os.WriteFile(dir+"/untracked.txt",[]byte("A"),0600);a,e1:=Key(context.Background(),dir);os.WriteFile(dir+"/untracked.txt",[]byte("B"),0600);b,e2:=Key(context.Background(),dir);fmt.Printf("key_before=%s\\nkey_after=%s\\nkey_equal=%t errors=%v,%v\\n",a,b,a==b,e1,e2)}\n`);
results.push({id:'P07',command:'go run key.go <fixture> — Key unchanged; only package/import and error-format adapter for standalone execution',...run('go',['run',out+'/key.go',fixture])});
const rules=JSON.parse(fs.readFileSync(out+'/inventory.json')).filter(x=>x.path.startsWith('.claude/rules/'));
results.push({id:'P08',command:'Read every rule file; count paths frontmatter absence and UTF-8 bytes',output:JSON.stringify({files:rules.length,lines:rules.reduce((s,f)=>s+f.lines,0),bytes:rules.reduce((s,f)=>s+f.bytes,0),no_paths_files:rules.filter(f=>!f.frontmatter||!/^paths:/m.test(f.frontmatter)).length,no_paths_bytes:rules.filter(f=>!f.frontmatter||!/^paths:/m.test(f.frontmatter)).reduce((s,f)=>s+f.bytes,0)},null,2)});
results.push({id:'P09',command:'Check literal snapshot consumer symbols in full hook and workflow source',output:JSON.stringify(Object.fromEntries(['.claude/hooks/moai/sync-phase-quality-gate.sh','.claude/workflows/sync-audit-4dim.js'].map(p=>[p,{verify_cli:fs.readFileSync(root+'/'+p,'utf8').includes('moai verify'),snapshot_term:/snapshot/i.test(fs.readFileSync(root+'/'+p,'utf8'))}]))),meaning:'직접 연결 구문 부재 확인. 런타임 외부 주입까지 부재라고 단정하지 않음.'});
fs.writeFileSync(out+'/probes.json',JSON.stringify(results,null,2));
for(const r of results) console.log(r.id+' '+JSON.stringify(r));
