package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var glmCmd = &cobra.Command{
	Use:   "glm [api-key]",
	Short: "Switch to GLM backend",
	Long: `Switch the active LLM backend to GLM by injecting env variables into .claude/settings.local.json.

If an API key is provided as an argument, it will be saved to ~/.moai/.env.glm
for future use. The key is stored securely with owner-only permissions (600).

This command reads GLM configuration from .moai/config/sections/llm.yaml and
injects the appropriate environment variables into Claude Code's settings.

Examples:
  moai glm                    # Use saved or environment API key
  moai glm sk-xxx-your-key    # Save API key and switch to GLM

Use 'moai cc' to switch back to Claude backend.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runGLM,
}

func init() {
	rootCmd.AddCommand(glmCmd)
}

// SettingsLocal represents .claude/settings.local.json structure.
type SettingsLocal struct {
	Meta                  map[string]any    `json:"_meta,omitempty"`
	EnabledMcpjsonServers []string          `json:"enabledMcpjsonServers,omitempty"`
	CompanyAnnouncements  []string          `json:"companyAnnouncements,omitempty"`
	Env                   map[string]string `json:"env,omitempty"`
	Permissions           map[string]any    `json:"permissions,omitempty"`
}

// runGLM switches the LLM backend to GLM by modifying settings.local.json.
func runGLM(cmd *cobra.Command, args []string) error {
	out := cmd.OutOrStdout()

	// If API key provided as argument, save it first
	if len(args) > 0 {
		apiKey := args[0]
		if err := saveGLMKey(apiKey); err != nil {
			return fmt.Errorf("save GLM API key: %w", err)
		}
		fmt.Fprintln(out, "✅ GLM API key saved to ~/.moai/.env.glm")
	}

	// Get project root
	root, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("find project root: %w", err)
	}

	// Load GLM config from llm.yaml
	glmConfig, err := loadGLMConfig(root)
	if err != nil {
		return fmt.Errorf("load GLM config: %w", err)
	}

	// Inject env into settings.local.json
	settingsPath := filepath.Join(root, ".claude", "settings.local.json")
	if err := injectGLMEnv(settingsPath, glmConfig); err != nil {
		return fmt.Errorf("inject GLM env: %w", err)
	}

	fmt.Fprintln(out, "✅ Switched to GLM backend.")
	fmt.Fprintln(out, "   Environment variables injected into .claude/settings.local.json")
	fmt.Fprintln(out, "   Run 'moai cc' to switch back to Claude.")
	return nil
}

// GLMConfigFromYAML represents the GLM settings from llm.yaml.
type GLMConfigFromYAML struct {
	BaseURL string
	Models  struct {
		Haiku  string
		Sonnet string
		Opus   string
	}
	EnvVar string
}

// loadGLMConfig reads GLM configuration from llm.yaml.
func loadGLMConfig(root string) (*GLMConfigFromYAML, error) {
	// If config is available via deps, use it
	if deps != nil && deps.Config != nil {
		cfg := deps.Config.Get()
		if cfg != nil && cfg.LLM.GLM.BaseURL != "" {
			return &GLMConfigFromYAML{
				BaseURL: cfg.LLM.GLM.BaseURL,
				Models: struct {
					Haiku  string
					Sonnet string
					Opus   string
				}{
					Haiku:  cfg.LLM.GLM.Models.Haiku,
					Sonnet: cfg.LLM.GLM.Models.Sonnet,
					Opus:   cfg.LLM.GLM.Models.Opus,
				},
				EnvVar: cfg.LLM.GLMEnvVar,
			}, nil
		}
	}

	// Fallback to default values
	return &GLMConfigFromYAML{
		BaseURL: "https://api.z.ai/api/anthropic",
		Models: struct {
			Haiku  string
			Sonnet string
			Opus   string
		}{
			Haiku:  "glm-4.7-flashx",
			Sonnet: "glm-4.7",
			Opus:   "glm-4.7",
		},
		EnvVar: "GLM_API_KEY",
	}, nil
}

// getGLMEnvPath returns the path to ~/.moai/.env.glm.
func getGLMEnvPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".moai", ".env.glm")
}

// saveGLMKey saves the GLM API key to ~/.moai/.env.glm.
func saveGLMKey(key string) error {
	envPath := getGLMEnvPath()
	if envPath == "" {
		return fmt.Errorf("cannot determine home directory")
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	// Escape special characters for dotenv format
	escapedKey := escapeDotenvValue(key)

	// Write in dotenv format
	content := fmt.Sprintf("# GLM API Key for MoAI-ADK\n# Generated by moai glm\nGLM_API_KEY=\"%s\"\n", escapedKey)
	if err := os.WriteFile(envPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}

// loadGLMKey loads the GLM API key from ~/.moai/.env.glm.
func loadGLMKey() string {
	envPath := getGLMEnvPath()
	if envPath == "" {
		return ""
	}

	file, err := os.Open(envPath)
	if err != nil {
		return ""
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		if strings.HasPrefix(line, "GLM_API_KEY=") {
			value := strings.TrimPrefix(line, "GLM_API_KEY=")
			// Remove quotes if present
			if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
				value = unescapeDotenvValue(value[1 : len(value)-1])
			} else if len(value) >= 2 && value[0] == '\'' && value[len(value)-1] == '\'' {
				value = value[1 : len(value)-1]
			}
			return value
		}
	}
	return ""
}

// escapeDotenvValue escapes special characters for dotenv double-quoted value.
func escapeDotenvValue(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "$", "\\$")
	return value
}

// unescapeDotenvValue unescapes dotenv double-quoted value.
func unescapeDotenvValue(value string) string {
	value = strings.ReplaceAll(value, "\\$", "$")
	value = strings.ReplaceAll(value, "\\\"", "\"")
	value = strings.ReplaceAll(value, "\\\\", "\\")
	return value
}

// getGLMAPIKey returns the GLM API key from multiple sources.
// Priority: 1. ~/.moai/.env.glm, 2. Environment variable GLM_API_KEY
func getGLMAPIKey(envVar string) string {
	// Check saved key first
	if key := loadGLMKey(); key != "" {
		return key
	}
	// Fall back to environment variable
	return os.Getenv(envVar)
}

// injectGLMEnv adds GLM environment variables to settings.local.json.
func injectGLMEnv(settingsPath string, glmConfig *GLMConfigFromYAML) error {
	// Get API key from saved file or environment
	apiKey := getGLMAPIKey(glmConfig.EnvVar)
	if apiKey == "" {
		return fmt.Errorf("GLM API key not found. Run 'moai glm <api-key>' to save your key, or set %s environment variable", glmConfig.EnvVar)
	}

	var settings SettingsLocal

	// Read existing settings if file exists
	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parse settings.local.json: %w", err)
		}
	}

	// Initialize env map if nil
	if settings.Env == nil {
		settings.Env = make(map[string]string)
	}

	// Inject GLM environment variables with actual API key value
	settings.Env["ANTHROPIC_AUTH_TOKEN"] = apiKey
	settings.Env["ANTHROPIC_BASE_URL"] = glmConfig.BaseURL
	settings.Env["ANTHROPIC_DEFAULT_HAIKU_MODEL"] = glmConfig.Models.Haiku
	settings.Env["ANTHROPIC_DEFAULT_SONNET_MODEL"] = glmConfig.Models.Sonnet
	settings.Env["ANTHROPIC_DEFAULT_OPUS_MODEL"] = glmConfig.Models.Opus

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	// Write back
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}

	if err := os.WriteFile(settingsPath, data, 0o644); err != nil {
		return fmt.Errorf("write settings.local.json: %w", err)
	}

	return nil
}

// findProjectRoot finds the project root by looking for .moai directory.
func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, ".moai")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("not in a MoAI project (no .moai directory found)")
		}
		dir = parent
	}
}
