// Package glmcred owns the single implementation of the GLM API credential
// writer and reader for ~/.moai/.env.glm.
//
// @MX:ANCHOR: [AUTO] GLM credential SSOT — exactly one writer implementation
// @MX:REASON: two writers would mean two file-mode policies and two escaping rules; both internal/cli (moai glm) and internal/web (settings console) MUST delegate here (SPEC-GLM-KEY-INPUT-001 D-1 / C-2)
//
// The package depends only on the standard library and stdlib-only internal
// leaf packages (internal/paths, internal/defs) so it cannot participate in
// any import cycle. It is imported by both internal/cli (the interactive
// `moai glm` flow) and internal/web (the settings console key field), which
// together require the one-way dependency internal/cli → internal/web to stay
// acyclic.
package glmcred

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/modu-ai/moai-adk/internal/defs"
	"github.com/modu-ai/moai-adk/internal/paths"
)

// EnvTestGLMKey is the env-var test seam honoured by Load. A non-empty value
// short-circuits the on-disk read and is returned verbatim, so tests can
// simulate a stored key without touching ~/.moai/.env.glm. The constant string
// itself is owned by internal/config/envkeys.go (config.EnvTestGLMKey) — this
// alias keeps the seam working after extraction without introducing a second
// literal.
const EnvTestGLMKey = "MOAI_TEST_GLM_KEY"

// HomeDirFn resolves the operator's home directory. It is a function variable
// (mirroring the userHomeDirFn pattern in internal/cli) so tests can redirect
// it at a t.TempDir() and never touch the developer's real home directory.
// The default resolves HOME-first through internal/paths
// (SPEC-V3R6-MOAI-HOME-PATHS-001 REQ-MHP-010), aligning web consumers with
// the single home-resolution contract.
var HomeDirFn = paths.Home

// Path returns the absolute path to the GLM credential file (~/.moai/.env.glm).
// A non-empty absolute MOAI_HOME redirects the file under the overridden root
// (REQ-MHP-001, resolved through internal/paths); otherwise the preserved
// HomeDirFn seam resolves the home and the join consumes defs segments
// (REQ-MHP-010). It returns the empty string when resolution fails.
func Path() string {
	if v := os.Getenv(paths.EnvHome); v != "" && filepath.IsAbs(v) {
		p, err := paths.GlmEnvFile()
		if err != nil {
			return ""
		}
		return p
	}
	home, err := HomeDirFn()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, defs.MoAIDir, defs.GlmEnvFileName)
}

// Save writes the GLM API key to ~/.moai/.env.glm at file mode 0600, in the
// quoted GLM_API_KEY dotenv form the existing reader produces.
//
// On a pre-existing file whose mode is wider than 0600, the mode is tightened
// to 0600 as part of the write (REQ-GKI-006-002). os.WriteFile's perm argument
// applies only at file creation, so an existing 0644 file would otherwise stay
// 0644 — this is the latent defect closed by the explicit Chmod.
func Save(key string) error {
	envPath := Path()
	if envPath == "" {
		return fmt.Errorf("cannot determine home directory")
	}

	if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	escaped := EscapeValue(key)
	content := fmt.Sprintf("# GLM API Key for MoAI-ADK\n# Generated by moai glm\nGLM_API_KEY=\"%s\"\n", escaped)
	if err := os.WriteFile(envPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	// Explicit mode assertion: os.WriteFile's perm is honoured only at file
	// creation. An existing ~/.moai/.env.glm created at a wider mode by an
	// older writer is narrowed here to 0600 so the credential is never
	// world-readable after a save.
	if err := os.Chmod(envPath, 0o600); err != nil {
		return fmt.Errorf("chmod credential file: %w", err)
	}
	return nil
}

// Load reads the GLM API key from ~/.moai/.env.glm.
//
// The EnvTestGLMKey env var is honoured first (test seam — C-4) and short-
// circuits the on-disk read. When the credential file is absent or unreadable,
// or carries no GLM_API_KEY entry, Load returns the empty string.
func Load() string {
	if testKey := os.Getenv(EnvTestGLMKey); testKey != "" {
		return testKey
	}

	envPath := Path()
	if envPath == "" {
		return ""
	}

	file, err := os.Open(envPath)
	if err != nil {
		return ""
	}
	defer func() { _ = file.Close() }()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		if after, ok := strings.CutPrefix(line, "GLM_API_KEY="); ok {
			value := after
			if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
				value = UnescapeValue(value[1 : len(value)-1])
			} else if len(value) >= 2 && value[0] == '\'' && value[len(value)-1] == '\'' {
				value = value[1 : len(value)-1]
			}
			return value
		}
	}
	return ""
}

// EscapeValue escapes the characters that are special inside a dotenv
// double-quoted value: backslash, double-quote, and dollar. It deliberately
// does NOT escape newlines — a newline in an API key is malformed input that
// the boundary validator (internal/web) rejects, not a value to round-trip.
func EscapeValue(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "$", "\\$")
	return value
}

// UnescapeValue reverses EscapeValue.
func UnescapeValue(value string) string {
	value = strings.ReplaceAll(value, "\\$", "$")
	value = strings.ReplaceAll(value, "\\\"", "\"")
	value = strings.ReplaceAll(value, "\\\\", "\\")
	return value
}
