package session

// ignored_content.go — SPEC-WORKTREE-REAPER-001 REQ-WR-024, the ignored-content
// decision, shared by every sweep that removes a worktree.
//
// It lives here for the same reason the anchor decision does (REQ-WR-019): a
// second copy in the second consumer is a second thing to keep in agreement
// forever, and the first divergence is silent — the sweep that lacks the guard
// destroys content, exit 0, with nothing in its output to read afterwards.
//
// Why the guard exists at all: `git status --porcelain` and non-forced
// `git worktree remove` AGREE in disregarding ignored files (design.md §A.6,
// measured), so the dirty guard has no backstop for this class. This decision
// is the only thing between a sweep and that loss.

import "strings"

// RegenerableIgnoredPaths is the allowlist of gitignored paths whose loss
// costs nothing, enumerated FROM the measurement rather than invented ahead of
// it (design.md §A.7.3): runtime state, runtime-managed config, build output,
// and test residue. Every ignored path outside this list — including one
// nobody has classified — preserves the worktree (REQ-WR-024, fail-closed).
//
// The list is NOT the inverse of "valuable". It is the inverse of
// "regenerable": an entry belongs here when something reproduces it — a build,
// a runtime write, a re-run — not when its content happens to be uninteresting.
//
// [HARD] Do not extend this list by omission. A path is added here only after
// it is observed AND shown to be reproduced by a build, a runtime write, or a
// re-run.
var RegenerableIgnoredPaths = []string{
	".moai/state",
	".moai/logs",
	// Regenerated by the SessionStart hook from ~/.moai/.env.glm and the
	// per-machine launcher state; it carries credentials, so it is
	// allowlisted as REPRODUCIBLE, never as unimportant (F6).
	".claude/settings.local.json",
	".claude/settings.local.json.lock",
	"bin",
	"docs-site/public",
	".ruff_cache",
	"internal/cli/.moai",
}

// IrreplaceableIgnoredEntries returns the `git status --porcelain --ignored`
// entries that are NOT covered by RegenerableIgnoredPaths. An empty result
// means every ignored entry is regenerable and the tree is safe to remove.
//
// @MX:ANCHOR: [AUTO] the sole ignored-content predicate behind every sweep
// @MX:REASON: all three SWEEPS consult it — prMergeCleanup, `worktree clean
// --stale`, and `worktree clean --merged-only`; an entry it fails to classify
// as irreplaceable is deleted with the worktree and cannot be recovered.
// `worktree done` and `worktree remove` are deliberately outside it: each acts
// on one named target the operator chose, not on a population it enumerated.
// `done --auto` is the weakest of that exclusion — it runs unattended after a
// PR merge — and is left to a follow-up card rather than widened here.
func IrreplaceableIgnoredEntries(porcelain string) []string {
	var irreplaceable []string
	for _, line := range strings.Split(porcelain, "\n") {
		if !strings.HasPrefix(line, "!! ") {
			continue
		}
		entry := strings.Trim(strings.TrimSpace(strings.TrimPrefix(line, "!! ")), "\"")
		entry = strings.TrimSuffix(entry, "/")
		if entry == "" || IsRegenerableIgnoredPath(entry) {
			continue
		}
		irreplaceable = append(irreplaceable, entry)
	}
	return irreplaceable
}

// IsRegenerableIgnoredPath reports whether entry is at or below an allowlisted
// regenerable path.
func IsRegenerableIgnoredPath(entry string) bool {
	for _, p := range RegenerableIgnoredPaths {
		if entry == p || strings.HasPrefix(entry, p+"/") {
			return true
		}
	}
	return false
}
