mx:
  version: "1.0"
  exclude:
    - "**/*_generated.go"
    - "**/vendor/**"
    - "**/mock_*.go"
  limits:
    anchor_per_file: 3
    warn_per_file: 5
  thresholds:
    fan_in_anchor: 5
    complexity_warn: 15
    branch_warn: 8
  auto_tag: true
  require_reason_for:
    - ANCHOR
    - WARN
