# MoAI-ADK Project Makefile
# Generated by moai init — customize as needed.

.PHONY: help ci-local pr-merge

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

ci-local: ## Run CI mirror locally (lint + vet + test + cross-compile)
	@./scripts/ci-mirror/run.sh

pr-merge: ## Enable GitHub auto-merge for a PR (Usage: make pr-merge PR=N [STRATEGY=squash|merge])
	@test -n "$(PR)" || (printf 'Usage: make pr-merge PR=<number> [STRATEGY=squash|merge]\n' >&2 && exit 1)
	@gh pr merge $(PR) --auto --$(or $(STRATEGY),squash)

.DEFAULT_GOAL := help
