name: ci
on: [push]
jobs:
  Test:
    name: "Test (${{ matrix.os }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu 24.04", windows-latest]
    steps:
      - run: "true"
