// Package commandemit implements the deterministic publication of the /moai
// command sources as codex skill-shaped artifacts
// (SPEC-CODEX-COMMAND-SKILLS-001).
//
// The command sources under .claude/commands/moai/ are consumed READ-ONLY:
// the publication is one SKILL.md per command under .agents/skills/moai-<command>/,
// whose frontmatter carries the derived name and the English description
// variant, and whose body is the source body verbatim — byte-identical, never
// re-rendered or repaired (the body's known Claude-only tooling reference is
// recorded as a boundary flag, not fixed here; the command-body layer owns
// that repair).
//
// The emitter is fail-closed: a missing frontmatter delimiter, a missing
// description, a locale-conditional description with no unconditional branch,
// or a derived skill name colliding with an existing canonical skill
// directory aborts emission with a diagnostic naming the offending file and
// value, and no partial artifact set is produced.
package commandemit

// EnvUpdate is the environment switch that flips the golden test into
// regeneration mode (the maintainer path); unset or empty, the golden test
// compares instead of writing.
const EnvUpdate = "COMMAND_EMIT_UPDATE"

// GeneratedHeader is the provenance line carried INSIDE the emitted YAML
// frontmatter (not the body — the body must stay byte-identical to the
// source body). Neutral English, no internal identifiers or dates.
const GeneratedHeader = "Generated by the MoAI command-to-skill publisher; regenerate, do not edit."

// BoundaryFlag is the per-skill note recorded in the emission report: the
// published body is the command source body verbatim and references
// Claude-only tooling. Publication records it; repair belongs to the
// command-body layer.
const BoundaryFlag = "published body is verbatim from the Claude command source and references Claude-only tooling (Skill(\"moai\")) — flagged, not repaired"

// Options selects the roots the emitter reads from and writes into, all
// fs-relative (forward-slash) paths under the template tree.
type Options struct {
	// CommandsRoot is the command source directory (read-only input).
	CommandsRoot string
	// SkillsRoot is the canonical skill directory whose directory names the
	// derived skill names must not collide with (read-only input).
	SkillsRoot string
	// EmittedRoot is the published-skills root the artifacts land under.
	EmittedRoot string
}

// DefaultOptions returns the options for the real template tree.
func DefaultOptions() Options {
	return Options{
		CommandsRoot: ".claude/commands/moai",
		SkillsRoot:   ".claude/skills",
		EmittedRoot:  ".agents/skills",
	}
}

// CommandDoc is the parsed neutral form of one command source.
type CommandDoc struct {
	// File is the source file name (base), e.g. "plan.md.tmpl" or "todo.md".
	File string
	// Command is the command name (file stem), e.g. "plan" or "todo".
	Command string
	// SkillName is the derived published-skill name: "moai-" + Command.
	SkillName string
	// Description is the language-neutral English variant of the source
	// description, carrying no Go template syntax.
	Description string
	// Body is the verbatim body bytes after the closing frontmatter delimiter.
	Body []byte
}

// SkillReport is the per-skill outcome of one emission run.
type SkillReport struct {
	// Command is the source command name.
	Command string
	// Skill is the derived published-skill name.
	Skill string
	// Path is the emitted path (forward-slash, template-tree relative).
	Path string
	// Description is the published English description.
	Description string
	// BoundaryFlag records that the body references Claude-only tooling
	// (always BoundaryFlag; present as a field so the report is explicit).
	BoundaryFlag string
}

// Publication is the deterministic publication of the command set.
type Publication struct {
	// Skills maps each emitted path (forward-slash, e.g.
	// ".agents/skills/moai-plan/SKILL.md") to its deterministic rendering.
	Skills map[string][]byte
	// Report carries one entry per published skill, in source-name order.
	Report []SkillReport
}
