# MoAI-ADK Progressive Disclosure System
# Three-level knowledge loading system for efficient token management
# Version: 1.0.0
# Last Updated: 2026-01-22

---
system:
  version: "1.0.0"
  description: "3-level progressive disclosure system for efficient skill loading"
  benefit: "67% reduction in initial token load (from ~90K to ~600 tokens)"

# Level Definitions
levels:
  level1:
    name: "Metadata Only"
    description: "YAML frontmatter with triggers"
    tokens: "~100"
    loading: "Always loaded for skills in agent frontmatter"
    content:
      - "name"
      - "description"
      - "version"
      - "category"
      - "triggers"
      - "progressive_disclosure.enabled"
    examples:
      - "Agent initialization"
      - "Skill catalog browsing"
      - "Trigger condition matching"

  level2:
    name: "Skill Body"
    description: "Full markdown documentation"
    tokens: "~5000"
    loading: "Loaded when trigger conditions match"
    content:
      - "Full markdown documentation"
      - "Implementation guides"
      - "Code examples"
      - "Best practices"
    examples:
      - "Keyword match in user prompt"
      - "Specific agent activation"
      - "Workflow phase match"
      - "Language detection"

  level3:
    name: "Bundled Files"
    description: "On-demand reference materials"
    tokens: "unlimited"
    loading: "Loaded by Claude decision when needed"
    content:
      - "reference.md"
      - "modules/"
      - "examples/"
      - "templates/"
    examples:
      - "Deep dive into specific topic"
      - "Reference documentation lookup"
      - "Example code patterns"

# Trigger Configuration
triggers:
  keywords:
    type: "array"
    description: "Keywords that trigger Level 2 loading"
    examples:
      foundation: ["trust-5", "spec-first", "ddd", "delegation", "agent"]
      workflow: ["spec", "ears", "requirement", "user story", "planning"]
      language_python: ["Python", "Django", "FastAPI", "Flask", "asyncio"]
      language_typescript: ["TypeScript", "React", "Next.js", "tRPC", "Zod"]
      backend: ["API", "database", "authentication", "JWT", "OAuth"]
      frontend: ["React", "Vue", "UI", "component", "state management"]

  agents:
    type: "array"
    description: "Agents that auto-load this skill"
    examples:
      foundation: ["manager-spec", "manager-ddd", "manager-strategy", "manager-quality"]
      workflow_spec: ["manager-spec", "Plan"]
      workflow_ddd: ["manager-ddd", "manager-strategy"]
      language_python: ["expert-backend", "expert-testing"]

  phases:
    type: "array"
    description: "Workflow phases that trigger Level 2 loading"
    enum:
      - "plan"
      - "run"
      - "sync"
      - "all"
    examples:
      plan: ["manager-spec", "manager-strategy"]
      run: ["manager-ddd", "expert-backend", "expert-frontend"]
      sync: ["manager-docs"]

  languages:
    type: "array"
    description: "Programming languages that trigger Level 2 loading"
    examples:
      python: ["python", "py", "fastapi", "django"]
      typescript: ["typescript", "ts", "react", "next.js"]
      go: ["go", "golang", "fiber", "gin"]
      java: ["java", "spring", "maven", "gradle"]

# Category-Specific Trigger Patterns
category_patterns:
  foundation:
    keywords:
      - "trust-5"
      - "spec-first"
      - "ddd"
      - "delegation"
      - "agent"
      - "token"
      - "progressive disclosure"
      - "modular"
      - "workflow"
      - "orchestration"
      - "quality gate"
    agents:
      - "manager-spec"
      - "manager-ddd"
      - "manager-strategy"
      - "manager-quality"
      - "builder-agent"
      - "builder-command"
      - "builder-skill"
    phases:
      - "plan"
      - "run"
      - "sync"

  workflow:
    keywords:
      - "spec"
      - "ears"
      - "requirement"
      - "acceptance criteria"
      - "user story"
      - "planning"
      - "ddd"
      - "refactoring"
      - "testing"
      - "documentation"
    agents:
      - "manager-spec"
      - "manager-ddd"
      - "manager-docs"
      - "manager-quality"
      - "manager-testing"
    phases: "all"

  language:
    python:
      keywords: ["Python", "Django", "FastAPI", "Flask", "asyncio", "pytest", "pyproject.toml"]
      languages: ["python"]
    typescript:
      keywords: ["TypeScript", "React", "Next.js", "tRPC", "Zod", "tsx"]
      languages: ["typescript", "javascript"]
    go:
      keywords: ["Go", "golang", "Fiber", "Gin", "GORM", "go.mod"]
      languages: ["go"]
    java:
      keywords: ["Java", "Spring", "Maven", "Gradle", "JUnit", " Jakarta"]
      languages: ["java"]

  domain:
    backend:
      keywords: ["API", "backend", "database", "authentication", "JWT", "OAuth", "REST", "GraphQL"]
    frontend:
      keywords: ["frontend", "UI", "component", "React", "Vue", "state management", "CSS"]
    database:
      keywords: ["database", "SQL", "NoSQL", "PostgreSQL", "MongoDB", "Redis", "ORM"]

  platform:
    auth0:
      keywords: ["Auth0", "authentication", "MFA", "attack protection"]
    firebase:
      keywords: ["Firebase", "Google auth", "phone auth", "social auth"]
    supabase:
      keywords: ["Supabase", "PostgreSQL", "real-time", "RLS"]

# JIT Integration
jit_integration:
  description: "Seamless integration with phase-based loading"
  token_budget_estimation: "Based on agent skills and phase"
  loading_strategy:
    level1: "Load all agent skill frontmatters at initialization"
    level2: "Load skill bodies when triggers match during execution"
    level3: "Load bundled files on-demand based on Claude decision"

# Best Practices
best_practices:
  trigger_design:
    - "Use specific keywords to avoid false positives"
    - "Include 5-10 keywords per skill"
    - "Match keywords to user's natural language"
    - "Include framework names and common terms"
    - "Consider phase-specific triggers for workflows"

  token_estimation:
    - "Level 1: ~100 tokens (metadata only)"
    - "Level 2: ~5000 tokens (full documentation)"
    - "Level 3: Variable (on-demand references)"
    - "Overestimate by 10-20% for safety margin"

  category_alignment:
    - "Foundation skills: Load early, keep accessible"
    - "Workflow skills: Load by phase dependency"
    - "Language skills: Load by code detection"
    - "Platform skills: Load by service mention"

# Examples
examples:
  minimal_trigger:
    skill: "moai-library-mermaid"
    progressive_disclosure:
      enabled: true
      level1_tokens: 100
      level2_tokens: 5000
    triggers:
      keywords: ["mermaid", "diagram", "flowchart", "sequence"]

  comprehensive_trigger:
    skill: "moai-foundation-core"
    progressive_disclosure:
      enabled: true
      level1_tokens: 100
      level2_tokens: 5000
    triggers:
      keywords: ["trust-5", "spec-first", "ddd", "delegation", "agent"]
      agents: ["manager-spec", "manager-ddd", "manager-strategy", "manager-quality"]
      phases: ["plan", "run", "sync"]

  language_trigger:
    skill: "moai-lang-python"
    progressive_disclosure:
      enabled: true
      level1_tokens: 100
      level2_tokens: 5000
    triggers:
      keywords: ["Python", "Django", "FastAPI", "Flask", "asyncio"]
      languages: ["python"]

# Validation Rules
validation:
  required_fields:
    - "progressive_disclosure.enabled"
    - "progressive_disclosure.level1_tokens"
    - "progressive_disclosure.level2_tokens"
    - "triggers.keywords (min 1 item)"

  keyword_rules:
    - "Keywords must be lowercase or match common casing"
    - "No special characters except hyphens for compound terms"
    - "Minimum 3 characters per keyword"

  trigger_combination:
    - "At least one trigger type must be specified"
    - "Multiple trigger types use OR logic"
    - "Within array triggers use AND logic"

# Migration Guide
migration:
  from_static:
    description: "Converting static skills to progressive disclosure"
    steps:
      1: "Add progressive_disclosure section to frontmatter"
      2: "Define trigger keywords for your skill"
      3: "Specify relevant agents if applicable"
      4: "Add phase triggers for workflow skills"
      5: "Add language triggers for language skills"
      6: "Estimate token budgets for level1 and level2"
      7: "Test trigger conditions with sample prompts"

  best_practices:
    - "Start with minimal triggers, expand based on usage"
    - "Monitor trigger accuracy and adjust keywords"
    - "Keep level1_tokens under 150 for efficiency"
    - "Keep level2_tokens under 10000 for performance"
