# MoAI-ADK Skill Frontmatter Schema
# Single Source of Truth for all skill metadata structure
# Version: 1.0.0
# Last Updated: 2026-01-22

---
schema:
  version: "1.0.0"
  description: "YAML frontmatter schema for MoAI-ADK skills"
  strict: true

# Required Fields
required:
  - name
  - description
  - version
  - category
  - updated
  - status
  - allowed-tools

# Optional Fields
optional:
  - modularized
  - user-invocable
  - context
  - agent
  - author
  - tags
  - progressive_disclosure
  - triggers

# Field Definitions
fields:
  name:
    type: "string"
    pattern: "^moai-[a-z]+-[a-z-]+$"
    description: "Skill identifier following naming convention"
    examples:
      - "moai-foundation-core"
      - "moai-lang-python"
      - "moai-workflow-spec"
      - "moai-platform-auth0"

  description:
    type: "string"
    max_length: 1024
    description: "Clear description of skill purpose and use cases"
    template: "{category} {specialization} covering {topics}. Use when {use_case}."

  version:
    type: "string"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    description: "Semantic version following SemVer 2.0.0"
    examples:
      - "1.0.0"
      - "2.5.0"

  category:
    type: "string"
    enum:
      - "foundation"    # Core principles and architecture
      - "workflow"      # Development workflows and processes
      - "domain"        # Domain-specific expertise
      - "language"      # Programming language specialists
      - "platform"      # Platform and service integrations
      - "library"       # Library and framework guides
      - "tool"          # Tool-specific utilities
    description: "Skill category for organization and discovery"

  modularized:
    type: "boolean"
    default: false
    description: "Whether skill content is split into modular files"

  user-invocable:
    type: "boolean"
    default: false
    description: "Whether users can invoke this skill directly via slash command"

  context:
    type: "string"
    enum:
      - "fork"      # Runs in isolated context
      - "shared"    # Shares conversation context
    default: "shared"
    description: "Context isolation mode for skill execution"

  agent:
    type: "string"
    description: "Primary agent that uses this skill"
    examples:
      - "Plan"
      - "manager-spec"
      - "manager-ddd"

  author:
    type: "string"
    description: "Skill author or team"
    examples:
      - "MoAI-ADK Team"
      - "Community Contributor"

  tags:
    type: "array"
    items:
      type: "string"
    description: "Keywords for skill discovery and categorization"
    min_items: 3
    max_items: 10

  updated:
    type: "string"
    pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    description: "Last update date in ISO format (YYYY-MM-DD)"

  status:
    type: "string"
    enum:
      - "active"       # Fully functional and recommended
      - "experimental" # Testing phase, may change
      - "deprecated"   # Replaced by newer skill
    default: "active"
    description: "Current status of the skill"

  allowed-tools:
    type: "array"
    items:
      type: "string"
      enum:
        - "Read"
        - "Write"
        - "Edit"
        - "Grep"
        - "Glob"
        - "Bash"
        - "TodoWrite"
        - "AskUserQuestion"
        - "Task"
        - "mcp__context7__resolve-library-id"
        - "mcp__context7__get-library-docs"
        - "mcp__sequential-thinking__sequentialthinking"
    description: "Tools this skill is allowed to use"

# Progressive Disclosure Configuration
progressive_disclosure:
  enabled:
    type: "boolean"
    default: true
    description: "Enable 3-level progressive disclosure system"

  level1_tokens:
    type: "integer"
    default: 100
    description: "Token budget for Level 1 (metadata only)"

  level2_tokens:
    type: "integer"
    default: 5000
    description: "Token budget for Level 2 (full skill body)"

# Trigger Conditions
triggers:
  keywords:
    type: "array"
    items:
      type: "string"
    description: "Keywords that trigger Level 2 loading"
    min_items: 1

  agents:
    type: "array"
    items:
      type: "string"
    description: "Agents that auto-load this skill"
    examples:
      - ["manager-spec", "manager-ddd"]
      - ["expert-backend", "expert-frontend"]

  phases:
    type: "array"
    items:
      type: "string"
    enum:
      - "plan"
      - "run"
      - "sync"
      - "all"
    description: "Workflow phases that trigger Level 2 loading"

  languages:
    type: "array"
    items:
      type: "string"
    description: "Programming languages that trigger Level 2 loading"
    examples:
      - ["python"]
      - ["typescript", "javascript"]

# Category-Specific Defaults
category_defaults:
  foundation:
    modularized: true
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "mcp__context7__resolve-library-id"
      - "mcp__context7__get-library-docs"

  workflow:
    modularized: true
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Write"
      - "Edit"
      - "Grep"
      - "Glob"
      - "Bash"
      - "TodoWrite"

  domain:
    modularized: false
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "Bash"

  language:
    modularized: false
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "Bash"
      - "mcp__context7__resolve-library-id"
      - "mcp__context7__get-library-docs"

  platform:
    modularized: false
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "Bash"
      - "Write"
      - "Edit"

  library:
    modularized: false
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"

  tool:
    modularized: false
    user-invocable: false
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "Bash"

# Validation Rules
validation:
  name_pattern:
    rule: "Must follow moai-{category}-{name} convention"
    regex: "^moai-[a-z]+-[a-z-]+$"

  description_length:
    rule: "Must be between 50 and 1024 characters"
    min: 50
    max: 1024

  tags_relevance:
    rule: "Tags must include category and specialization keywords"
    check: "tags must contain at least one category keyword"

  version_format:
    rule: "Must follow SemVer 2.0.0 (MAJOR.MINOR.PATCH)"
    regex: "^[0-9]+\\.[0-9]+\\.[0-9]+$"

# Examples
examples:
  foundation_skill:
    name: "moai-foundation-core"
    description: "MoAI-ADK's foundational principles - TRUST 5, SPEC-First DDD, delegation patterns"
    version: "2.5.0"
    category: "foundation"
    modularized: true
    user-invocable: false
    tags: ["foundation", "core", "orchestration", "trust-5"]
    updated: "2026-01-21"
    status: "active"
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
    progressive_disclosure:
      enabled: true
      level1_tokens: 100
      level2_tokens: 5000
    triggers:
      keywords: ["trust-5", "spec-first", "ddd"]
      agents: ["manager-spec", "manager-ddd"]
      phases: ["plan", "run", "sync"]

  language_skill:
    name: "moai-lang-python"
    description: "Python 3.13+ development specialist covering FastAPI, Django, async patterns"
    version: "1.1.0"
    category: "language"
    modularized: false
    user-invocable: false
    tags: ["language", "python", "fastapi", "django"]
    updated: "2026-01-11"
    status: "active"
    allowed-tools:
      - "Read"
      - "Grep"
      - "Glob"
      - "Bash"
    progressive_disclosure:
      enabled: true
      level1_tokens: 100
      level2_tokens: 5000
    triggers:
      keywords: ["Python", "Django", "FastAPI"]
      languages: ["python"]
