// Resolution: KEEP — SPEC detect, session title, workflow keyword routing.
package hook

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/modu-ai/moai-adk/internal/workflow"
)

// specFilePattern is the glob pattern for finding spec.md files in SPEC directories.
const specFilePattern = ".moai/specs/*/spec.md"

// promptPreviewMaxLen is the maximum length of prompt preview in logs.
const promptPreviewMaxLen = 100

// titleMaxRunes is the maximum number of runes in a derived session title before
// truncation. The transcript text is often Korean, so the limit is measured in
// runes (not bytes) to avoid splitting a multi-byte character.
const titleMaxRunes = 60

// titleMinRunes is the minimum rune count for a derived title to be usable;
// shorter results (empty or a single character) are discarded.
const titleMinRunes = 2

// titleEllipsis is appended to a derived title only when truncation occurs.
const titleEllipsis = "…" // U+2026 HORIZONTAL ELLIPSIS

// transcriptMaxLineBytes is the per-line scanner buffer ceiling. Transcript
// lines (tool outputs) can be very long, so the buffer is raised well above the
// bufio default of 64 KiB. A line exceeding this ceiling is skipped, not errored.
const transcriptMaxLineBytes = 8 * 1024 * 1024 // 8 MiB

// userPromptSubmitHandler handles UserPromptSubmit events.
// It generates a content-bearing session title and returns it to Claude Code.
type userPromptSubmitHandler struct {
	cfg ConfigProvider
}

// NewUserPromptSubmitHandler creates a new UserPromptSubmit event handler.
func NewUserPromptSubmitHandler(cfg ConfigProvider) Handler {
	return &userPromptSubmitHandler{cfg: cfg}
}

// EventType returns EventUserPromptSubmit.
func (h *userPromptSubmitHandler) EventType() EventType {
	return EventUserPromptSubmit
}

// workflowKeywords are prompt keywords that indicate an active MoAI workflow context.
var workflowKeywords = []string{"loop", "run", "plan"}

// detectWorkflowContext checks whether the prompt contains any workflow keywords
// and returns a non-empty additionalContext string if a match is found.
func detectWorkflowContext(prompt string) string {
	lower := strings.ToLower(prompt)
	for _, kw := range workflowKeywords {
		if strings.Contains(lower, kw) {
			return "workflow keyword '" + kw + "' detected — MoAI workflow context may be active"
		}
	}
	return ""
}

// Handle processes a UserPromptSubmit event.
// It builds a content-bearing session title (from an active SPEC or the first
// user prompt in the transcript) and returns it via hookSpecificOutput.
// Errors are silently handled; an empty title is returned without blocking the
// prompt so the hook never stalls the user's Claude Code session.
func (h *userPromptSubmitHandler) Handle(ctx context.Context, input *HookInput) (*HookOutput, error) {
	// Log prompt for audit purposes (truncated to promptPreviewMaxLen chars)
	prompt := input.Prompt
	preview := prompt
	if len(preview) > promptPreviewMaxLen {
		preview = preview[:promptPreviewMaxLen] + "..."
	}
	slog.Info("user prompt submitted",
		"session_id", input.SessionID,
		"prompt_preview", preview,
	)

	// Build session title (errors are silently ignored, falls back to empty title)
	title := h.buildSessionTitle(ctx, input.CWD, input.TranscriptPath)

	// Detect workflow context
	additionalCtx := detectWorkflowContext(prompt)

	// Return empty output if no context to report
	if title == "" && additionalCtx == "" {
		return &HookOutput{}, nil
	}

	return &HookOutput{
		HookSpecificOutput: &HookSpecificOutput{
			HookEventName:     string(EventUserPromptSubmit),
			SessionTitle:      title,
			AdditionalContext: additionalCtx,
		},
	}, nil
}

// buildSessionTitle generates a content-bearing, session-stable title.
//
// Policy, in order:
//  1. Active SPEC → "SPEC-ID: heading" (content-bearing and stable).
//  2. No SPEC, ai-title already generated by Claude Code → "" (never shadow the
//     native LLM-quality title).
//  3. No SPEC, we already wrote a custom-title → "" (keep it stable — first-wins,
//     no churn).
//  4. No SPEC, transcript has a first user prompt but no title yet → derive a
//     title from that FIRST prompt (it defines the session topic).
//  5. No SPEC, no transcript / no user prompt found → "" (the session's first
//     prompt) so the native ai-title generator has a clear field.
//
// On any error the result is an empty string.
func (h *userPromptSubmitHandler) buildSessionTitle(ctx context.Context, cwd, transcriptPath string) string {
	// Case 1: an active SPEC yields a content-bearing, stable title.
	if cwd != "" {
		if title := detectActiveSpec(cwd); title != "" {
			return title
		}
	}

	// No SPEC. The title is derived from the transcript so it stays stable across
	// the session and never shadows Claude Code's native ai-title.
	//
	// conversation_language is read for explicitness and future use; the derived
	// title is already in the user's language because the user's own prompt is —
	// nothing is translated here.
	lang := h.conversationLanguage()

	facts := inspectTranscript(ctx, transcriptPath)
	switch {
	case facts.hasAITitle:
		// Case 2: never shadow the native ai-title.
		return ""
	case facts.hasCustomTitle:
		// Case 3: already titled by us; keep it stable (first-wins).
		return ""
	case facts.firstUserText != "":
		// Case 4: derive a stable title from the FIRST user prompt.
		title := deriveTitleFromPrompt(facts.firstUserText)
		slog.Debug("derived session title from transcript", "lang", lang, "title", title)
		return title
	default:
		// Case 5: session's first prompt (empty/absent transcript) — emit no
		// title so the native ai-title generator has a clear field.
		return ""
	}
}

// conversationLanguage returns the configured conversation_language, or "" when
// the config provider (or its config) is nil. It is nil-safe by contract because
// the handler must degrade gracefully rather than panic (hooks never block).
func (h *userPromptSubmitHandler) conversationLanguage() string {
	if h.cfg == nil {
		return ""
	}
	cfg := h.cfg.Get()
	if cfg == nil {
		return ""
	}
	return cfg.Language.ConversationLanguage
}

// detectActiveSpec searches cwd/.moai/specs/*/spec.md and returns the title
// of the most recently modified SPEC.
// Returns empty string if no SPEC is found or read fails.
func detectActiveSpec(cwd string) string {
	pattern := filepath.Join(cwd, specFilePattern)
	matches, err := filepath.Glob(pattern)
	if err != nil || len(matches) == 0 {
		return ""
	}

	// Select the most recently modified spec.md
	var latestMatch string
	var latestModTime int64
	for _, match := range matches {
		info, err := os.Stat(match)
		if err != nil {
			continue
		}
		mt := info.ModTime().UnixNano()
		if mt > latestModTime {
			latestModTime = mt
			latestMatch = match
		}
	}
	if latestMatch == "" {
		return ""
	}

	// Extract SPEC ID from directory name
	specDirName := filepath.Base(filepath.Dir(latestMatch))
	specID := workflow.SpecIDPattern.FindString(specDirName)
	if specID == "" {
		return ""
	}

	// Read the first heading (line starting with #) from spec.md
	heading := readFirstHeading(latestMatch)
	if heading == "" {
		return specID
	}

	// Strip SPEC-ID prefix from heading if already present (e.g., "SPEC-SRS-003: Dashboard...")
	if trimmed, ok := strings.CutPrefix(heading, specID+": "); ok {
		heading = trimmed
	} else if trimmed, ok := strings.CutPrefix(heading, specID); ok {
		heading = strings.TrimLeft(trimmed, ": ")
	}

	if heading == "" {
		return specID
	}

	return fmt.Sprintf("%s: %s", specID, heading)
}

// readFirstHeading returns the first # heading text from a markdown file.
func readFirstHeading(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if trimmed, ok := strings.CutPrefix(line, "# "); ok {
			return strings.TrimSpace(trimmed)
		}
	}
	return ""
}

// transcriptFacts carries the three facts extracted from a session transcript
// that the session-title policy needs.
type transcriptFacts struct {
	hasAITitle     bool   // a Claude Code native "ai-title" record is present
	hasCustomTitle bool   // a "custom-title" record (written by this hook) is present
	firstUserText  string // text of the FIRST "user" record, or "" if none found
}

// transcriptTitleMarker matches both "ai-title" and "custom-title" record types
// (both contain the substring "-title"). It is a cheap byte prefilter before the
// authoritative JSON decode.
var transcriptTitleMarker = []byte("-title")

// transcriptUserMarker matches "user" record types. It is a cheap byte prefilter
// before the authoritative JSON decode.
var transcriptUserMarker = []byte(`"user"`)

// transcriptLine is the minimal decode target for a single transcript JSONL
// record. Only the fields the title policy needs are decoded.
type transcriptLine struct {
	Type    string `json:"type"`
	Message struct {
		Role    string          `json:"role"`
		Content json.RawMessage `json:"content"`
	} `json:"message"`
}

// inspectTranscript streams the transcript at path line-by-line and extracts the
// three facts the title policy needs. It NEVER loads the whole file into memory
// (transcripts can exceed 1.5 MB) and NEVER errors: any failure (missing file,
// unreadable, malformed, oversized line) yields whatever facts were gathered so
// far, so the hook never blocks the prompt. It stops early once a title record
// (either kind) is found, since that forces an empty result regardless.
func inspectTranscript(ctx context.Context, path string) transcriptFacts {
	var facts transcriptFacts
	if path == "" {
		return facts
	}

	f, err := os.Open(path)
	if err != nil {
		return facts
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 64*1024), transcriptMaxLineBytes)

	for scanner.Scan() {
		// Honor cancellation / the ≤5s hook budget threaded via ctx.
		select {
		case <-ctx.Done():
			return facts
		default:
		}

		line := scanner.Bytes()

		// Cheap prefilters: skip the JSON decode for lines that cannot carry a
		// needed fact. Most lines are large assistant/tool records we ignore.
		needTitle := bytes.Contains(line, transcriptTitleMarker)
		needUser := facts.firstUserText == "" && bytes.Contains(line, transcriptUserMarker)
		if !needTitle && !needUser {
			continue
		}

		var rec transcriptLine
		if err := json.Unmarshal(line, &rec); err != nil {
			continue // malformed line — skip, do not error
		}

		switch rec.Type {
		case "ai-title":
			facts.hasAITitle = true
		case "custom-title":
			facts.hasCustomTitle = true
		case "user":
			if facts.firstUserText == "" {
				facts.firstUserText = transcriptContentText(rec.Message.Content)
			}
		}

		// A title record (either kind) forces an empty result — stop scanning.
		if facts.hasAITitle || facts.hasCustomTitle {
			break
		}
	}
	// scanner.Err() (including bufio.ErrTooLong on an oversized line) is
	// intentionally ignored: the hook returns the facts gathered so far.
	return facts
}

// transcriptContentText extracts plain text from a transcript record's
// message.content, which Claude Code encodes either as a plain string or as an
// array of content blocks ({"type":"text","text":"..."}). Unknown shapes yield "".
func transcriptContentText(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}

	// Common case: content is a plain string.
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		return s
	}

	// Alternative case: content is an array of content blocks.
	var blocks []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	}
	if err := json.Unmarshal(raw, &blocks); err == nil {
		var b strings.Builder
		for _, blk := range blocks {
			if blk.Text == "" {
				continue
			}
			if b.Len() > 0 {
				b.WriteByte(' ')
			}
			b.WriteString(blk.Text)
		}
		return b.String()
	}

	return ""
}

// directiveKeywordRE matches standalone MoAI directive keywords anywhere in the
// prompt: "ultrathink." (with trailing period), "ultrathink", and "ultracode".
// Word boundaries keep it from matching substrings (e.g. "ultrathinking").
var directiveKeywordRE = regexp.MustCompile(`(?i)\bultrathink\.|\bultrathink\b|\bultracode\b`)

// segmentTerminators end the first sentence / first line of a prompt. Newline is
// included so "first line" and "first sentence" collapse to a single earliest cut.
var segmentTerminators = []rune{'.', '?', '!', '。', '？', '！', '\n'} // . ? ! 。 ？ ！ \n

// deriveTitleFromPrompt turns a raw user prompt into a compact, content-bearing
// title. It is a pure string function — no LLM, no network, no translation. The
// title is naturally in the user's language because the prompt is.
//
// Steps: strip a leading slash-command token and standalone directive keywords;
// take the first sentence or first line (whichever is shorter); collapse
// whitespace; truncate to titleMaxRunes runes (appending an ellipsis only when
// truncation occurs). Returns "" if the result is empty or shorter than
// titleMinRunes runes.
func deriveTitleFromPrompt(prompt string) string {
	s := strings.TrimSpace(prompt)

	// 1a. Strip a leading slash-command token (e.g. "/moai plan ..." -> "plan ...").
	//     A bare slash command (e.g. "/clear") reduces to "".
	if strings.HasPrefix(s, "/") {
		if i := strings.IndexFunc(s, unicode.IsSpace); i >= 0 {
			s = strings.TrimLeftFunc(s[i:], unicode.IsSpace)
		} else {
			s = ""
		}
	}

	// 1b. Strip standalone directive keywords wherever they appear. This runs
	//     BEFORE sentence splitting so the trailing "." of "ultrathink." cannot
	//     prematurely terminate the first sentence. Newlines are preserved so the
	//     "first line" rule below still works.
	s = directiveKeywordRE.ReplaceAllString(s, "")

	// 2. First sentence or first line, whichever is shorter. Because the
	//    terminator set includes newline, cutting at the earliest terminator
	//    yields exactly that shorter segment.
	s = firstSegment(s)

	// 3. Collapse internal whitespace runs to a single space and trim.
	s = strings.Join(strings.Fields(s), " ")

	// 4. Truncate to at most titleMaxRunes runes (rune-safe), appending an
	//    ellipsis only when truncation actually occurred.
	s = truncateRunes(s, titleMaxRunes)

	// 5. Reject empty or too-short results.
	if utf8.RuneCountInString(s) < titleMinRunes {
		return ""
	}
	return s
}

// firstSegment returns the substring up to (excluding) the first segment
// terminator (see segmentTerminators), or the whole string if none is present.
func firstSegment(s string) string {
	for i, r := range s {
		for _, t := range segmentTerminators {
			if r == t {
				return s[:i]
			}
		}
	}
	return s
}

// truncateRunes truncates s to at most maxRunes runes, appending titleEllipsis
// only when truncation occurs. Slicing on the rune slice guarantees no multi-byte
// character is split.
func truncateRunes(s string, maxRunes int) string {
	runes := []rune(s)
	if len(runes) <= maxRunes {
		return s
	}
	return string(runes[:maxRunes]) + titleEllipsis
}
