#!/bin/bash
# MoAI-ADK Weekly Session Analysis Script
# Claude Code 세션 로그를 주간 분석하고 보고서 생성

set -e

PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$PROJECT_ROOT"

# 색상 정의
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📊 MoAI-ADK Weekly Session Analysis${NC}"
echo "=================================================="
echo "Project: $PROJECT_ROOT"
echo "Date: $(date)"
echo "=================================================="

# 1. 세션 분석 실행
echo -e "${BLUE}🔍 Running session analysis...${NC}"

REPORT_DIR=".moai/reports"
mkdir -p "$REPORT_DIR"

python3 .moai/scripts/session_analyzer.py \
  --days 7 \
  --output "$REPORT_DIR/weekly-$(date +%Y-%m-%d).md" \
  --verbose

echo -e "${GREEN}✅ Analysis complete${NC}"

# 2. 변경사항 확인
echo ""
echo -e "${BLUE}🔍 Checking for changes...${NC}"

if git diff --quiet HEAD "$REPORT_DIR/"; then
  echo -e "${YELLOW}⚠️  No changes to commit${NC}"
  exit 0
fi

# 3. 변경사항 커밋
echo -e "${BLUE}📝 Committing changes...${NC}"

git add "$REPORT_DIR/"

git commit -m "$(cat <<'EOF'
📊 Weekly session meta-analysis report

Generated by automated weekly analysis script.
Analyzing: Claude Code session logs from ~/.claude/projects/

Review improvements and update:
- .claude/settings.json (permissions)
- CLAUDE.md (rules and guidelines)
- .claude/hooks/ (hook logic)

🤖 Generated with Claude Code

Co-Authored-By: MoAI-ADK <moai@example.com>
EOF
)" || echo -e "${YELLOW}⚠️  Commit failed (might be empty)${NC}"

echo -e "${GREEN}✅ Analysis and commit complete${NC}"
echo ""
echo -e "${BLUE}📄 Report location: $REPORT_DIR/weekly-$(date +%Y-%m-%d).md${NC}"
