import json,pathlib,hashlib,datetime
root=pathlib.Path(__file__).resolve().parent
rows=[]
for p in sorted(root.glob('*.json')):
 if p.name.startswith(('sol-','astra-')):
  d=json.loads(p.read_text());u=d.get('usage') or {};rows.append({'model':d['model'],'repetitions':d['repetitions'],'input_tokens_observed':u.get('input_tokens'),'input_tokens_estimated':d['repetitions']+71,'output_tokens':u.get('output_tokens'),'total_tokens':u.get('total_tokens'),'cached_tokens':u.get('input_tokens_details',{}).get('cached_tokens'),'http_status':d.get('http_status'),'event':d.get('event'),'server_error_code':d.get('server_error_code'),'needle_recall':d.get('needle_recall'),'duration_seconds':d['duration_seconds'],'timeout':d.get('timeout'),'artifact':str(p.relative_to(root)),'log':'.runs/'+p.stem+'.log','command':f'T649_MODEL={d["model"]} T649_WORDS={d["repetitions"]} T649_RESULT={p} go test -overlay .moai/reports/t649/context-window-evidence/e2e/overlay.json ./internal/cli -run ^TestT649ContextLive$ -count=1 -v'})
models={}
for model in sorted({r['model'] for r in rows}):
 rr=[r for r in rows if r['model']==model];ok=[r for r in rr if r['event']=='response.completed' and r['needle_recall']];bad=[r for r in rr if r['server_error_code']=='context_length_exceeded'];lo=max(r['input_tokens_observed'] for r in ok);hi=min(r['input_tokens_estimated'] for r in bad);models[model]={'largest_observed_accepted_input_tokens':lo,'smallest_estimated_rejected_input_tokens':hi,'boundary_interval_tokens':hi-lo,'accepted_output_tokens':next(r['output_tokens'] for r in ok if r['input_tokens_observed']==lo)}
out={'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':{'head':'81c1d58f9','branch':'WT-unified-gateway','tree':'existing dirty worktree','probe_sha256':hashlib.sha256((root/'context_probe_test.go').read_bytes()).hexdigest()},'models':models,'journeys':rows,'gaps':['Rejected requests supply no server usage: N+71 is calibrated estimate, not observed usage.','Synthetic repeated ASCII and three needles do not prove real-project semantic quality or all-token retention.','No long-output test or explicit output reservation guarantee; server output policy used.','Direct subscription authorized transport bypasses MoAI local272000/1MiB limits and Claude UI; not production end-to-end window proof.','No tokenizer package; exact accepted token counts come from server usage.','Go test PASS means harness completed, not inference success; check event/needle/error.'],'residual_risk':['Server/account/model rollout can change limits.','No inferred1050000total context claim; observed input ceiling bracket only.'],'request_count':len(rows),'accepted_input_tokens_sum':sum(r['input_tokens_observed'] or 0 for r in rows)}
(root/'summary.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'models':models,'request_count':len(rows),'accepted_input_tokens_sum':out['accepted_input_tokens_sum']},indent=2))
