# goreleaser configuration for MoAI-ADK Go distribution
# Builds cross-platform binaries for 5 target platforms

project_name: moai

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./... -short

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/modu-ai/moai-adk/go/pkg/version.Version={{.Version}}
      - -s -w -X github.com/modu-ai/moai-adk/go/pkg/version.Commit={{.Commit}}
      - -s -w -X github.com/modu-ai/moai-adk/go/pkg/version.Date={{.Date}}
    main: ./cmd/moai/
    binary: moai-{{ .Os }}-{{ .Arch }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - scripts/install.sh

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: modu-ai
    name: moai-adk
  draft: false
  prerelease: auto
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - '^refactor:'

brews:
  - tap:
      owner: modu-ai
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/modu-ai/moai-adk
    description: MoAI Development Kit - Static binary distribution
    license: Apache-2.0
    test: |
      system "#{bin}/moai", "version"
    install: |
      bin.install "moai"

# SBOM generation (optional, for security compliance)
sboms:
  - artifacts: archive
    id: sbom
    documents:
      - "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}.sbom"

# Announce to various channels (optional)
announce:
  twitter:
    enabled: false
  mastodon:
    enabled: false
  discord:
    enabled: false
