// Package v4manifest — Runner Workflow template (design §F).
//
// RunnerTemplate is the dynamic-workflow script TEMPLATE that the Builder
// GENERATE phase stamps per-harness as harness-<name>-run.js. The template
// implements design §F dispatch pseudo-code verbatim:
//
//	read manifest.json
//	for each specialist in manifest.specialists:
//	    switch specialist.primitive:
//	        case "sub-agent":           Agent(specialist.role, ...)
//	        case "dynamic-workflow":    dynamicWorkflow(specialist.role, ...)
//	        case "worktree":            Agent(specialist.role, isolation:"worktree", ...)
//	        case "/goal":               goalDirective(specialist.role, ...)
//	        case "adversarial-fan-out": adversarialFanOut(specialist.role, ...)
//	    apply Sprint Contract (if evaluator not skipped)
//	emit cleanup directive (worktree cleanup if any isolation:worktree specialists)
//
// The Runner consumes specialist.primitive VERBATIM — no heuristic re-derivation
// (REQ-HV4-005 / AC-HV4-005b). The Sprint Contract (Generator-Evaluator
// separation) is applied per REQ-HV4-008; the evaluator is conditional.
//
// Storage decision (E8): the template lives as a Go-embedded string in this
// package (option a), NOT as a file under internal/template/templates/.claude/
// workflows/. Rationale: .claude/workflows/ is NOT a template surface today
// (pre-flight: find internal/template/templates/.claude/workflows returns
// nothing), and a Go-embedded string keeps the template out of the user-owned
// harness-* namespace at rest. The emitted per-harness harness-<name>-run.js
// is user-owned per M1 §24.4; the TEMPLATE the Builder stamps from is
// moai-distributable Go source.
//
// Determinism (C-HV4-003): the template body contains NO Date.now() or
// Math.random() calls. Timestamps are stamped onto results AFTER the run
// returns by the runtime, never generated inside the script body.
package v4manifest

// RunnerTemplate is the dynamic-workflow Runner script template. The Builder
// GENERATE phase writes this string (with the harness <name> substituted into
// the manifest.json read path) to .claude/workflows/harness-<name>-run.js.
//
// The template is generic and carries NO internal-state markers (C-HV4-005
// template neutrality): no SPEC IDs, REQ tokens, AC tokens, or commit SHAs.
//
// @MX:ANCHOR: [AUTO] RunnerTemplate is the single source of the Runner script body.
// @MX:REASON: [AUTO] fan_in >= 3 candidate: GENERATE phase stamp, Runner bootstrap, CI neutrality guard
const RunnerTemplate = `// harness-<name>-run.js — Runner Workflow (generated by the v4 Builder GENERATE phase).
//
// Reads manifest.json and dispatches specialists per their declared primitive.
// The Runner consumes specialist.primitive VERBATIM (no heuristic re-derivation).
// Deterministic script body: no wall-clock or random-number calls (resume-cache safe).

// readManifest is the SINGLE config-read path. The Runner reads ONLY
// manifest.json for its dispatch logic — no separate config file, no
// hard-coded specialist info.
function readManifest() {
  // The Builder GENERATE phase stamps the harness-specific manifest.json path
  // here. The path is the only per-harness substitution in this template.
  return readJson(".claude/commands/harness/<name>/manifest.json");
}

// dispatchSpecialist consumes specialist.primitive verbatim and dispatches
// accordingly (design §F). The switch is exhaustive over the 5 primitives;
// an unknown primitive is a manifest-validation failure (caught upstream).
function dispatchSpecialist(specialist, manifest) {
  switch (specialist.primitive) {
    case "sub-agent":
      return agent({
        label: specialist.role,
        effort: specialist.effort,
        model: specialist.model === "inherit" ? undefined : specialist.model,
        prompt: buildSpecialistPrompt(specialist, manifest)
      });
    case "dynamic-workflow":
      return agent({
        label: specialist.role,
        effort: specialist.effort,
        model: specialist.model === "inherit" ? undefined : specialist.model,
        prompt: buildSpecialistPrompt(specialist, manifest)
      });
    case "worktree":
      return agent({
        label: specialist.role,
        isolation: "worktree",
        effort: specialist.effort,
        model: specialist.model === "inherit" ? undefined : specialist.model,
        prompt: buildSpecialistPrompt(specialist, manifest)
      });
    case "/goal":
      return agent({
        label: specialist.role,
        effort: specialist.effort,
        model: specialist.model === "inherit" ? undefined : specialist.model,
        prompt: buildGoalPrompt(specialist, manifest)
      });
    case "adversarial-fan-out":
      return agent({
        label: specialist.role + " (adversarial)",
        effort: specialist.effort,
        model: specialist.model === "inherit" ? undefined : specialist.model,
        prompt: buildAdversarialPrompt(specialist, manifest)
      });
    default:
      // Unknown primitive — manifest validation should have caught this
      // upstream. The Runner does NOT re-derive the primitive.
      throw new Error("unknown primitive: " + specialist.primitive);
  }
}

// applySprintContract applies the Generator-Evaluator separation.
// The evaluator is CONDITIONAL: skipped when the task is within the model's
// solo reliable range (simple, well-bounded). The skip is recorded with
// rationale so a third party can audit the decision.
function applySprintContract(generated, manifest, taskProfile) {
  if (taskProfile.withinSoloRange) {
    // Evaluator skipped — task within model's solo range (C-HV4-001 simplest-
    // solution-first). Record the skip with rationale.
    return {
      evaluator: "skipped",
      rationale: "task within solo range, evaluator skipped per simplest-solution-first"
    };
  }
  // Evaluator invoked — tuned as a skeptical adversarial reviewer (not a
  // yes/no gate). The Sprint Contract dimensions + thresholds are applied.
  return {
    evaluator: "invoked",
    dimensions: manifest.sprint_contract.dimensions,
    thresholds: manifest.sprint_contract.thresholds,
    verdict: evaluateAgainstContract(generated, manifest.sprint_contract)
  };
}

// buildSpecialistPrompt, buildGoalPrompt, buildAdversarialPrompt,
// evaluateAgainstContract, and readJson are runtime-provided helpers. The
// template references them by name; the dynamic-workflow runtime injects the
// implementations. This keeps the template body deterministic and free of
// inline prompt text that would drift from the manifest's specialist.role.

// run is the entry point. It reads manifest.json, dispatches each specialist
// per primitive, applies the Sprint Contract (conditionally), and emits a
// cleanup directive if any specialist declared isolation:worktree.
function run(taskProfile) {
  const manifest = readManifest();
  const results = [];
  for (const specialist of manifest.specialists) {
    const generated = dispatchSpecialist(specialist, manifest);
    const contractResult = applySprintContract(generated, manifest, taskProfile);
    results.push({ specialist: specialist.role, primitive: specialist.primitive, contract: contractResult });
  }
  // Cleanup directive: worktree cleanup if any isolation:worktree specialists.
  const hasWorktreeIsolation = manifest.specialists.some(s => s.isolation === "worktree");
  if (hasWorktreeIsolation) {
    emitCleanupDirective("worktree-cleanup");
  }
  return results;
}
`
