package graph

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// fixtureProject builds a minimal project tree exercising all three edge
// layers and returns its root.
func fixtureProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()

	// Layer 1: codemaps import adjacency artifact (mermaid fence with labels).
	depDir := filepath.Join(root, ".moai", "project", "codemaps")
	if err := os.MkdirAll(depDir, 0o755); err != nil {
		t.Fatal(err)
	}
	depBody := `# 패키지 의존도 분석

> generated by /moai codemaps --force

## 의존도 그래프 (Mermaid)

` + "```mermaid" + `
graph TD
    cmd["cmd/moai<br/>main()"]
    cli["internal/cli"]
    config["internal/config"]
    mx["internal/mx"]
    lsp["internal/lsp"]
    astgrep["internal/astgrep"]

    cmd --> cli
    cli --> config
    cli --> mx
    mx --> lsp
    lsp -.-> astgrep
` + "```" + `

## 계층 간 의존도

**Presentation → Business → Infrastructure**
`
	if err := os.WriteFile(filepath.Join(depDir, "dependencies.md"), []byte(depBody), 0o644); err != nil {
		t.Fatal(err)
	}

	// Layer 2: @MX tag with @MX:SPEC sub-line.
	srcDir := filepath.Join(root, "internal", "demo")
	if err := os.MkdirAll(srcDir, 0o755); err != nil {
		t.Fatal(err)
	}
	goBody := `package demo

// @MX:ANCHOR: [AUTO] DemoAnchor — fixture anchor
// @MX:REASON: fixture reason
// @MX:SPEC:SPEC-GRAPH-TEST-001
func Demo() {}
`
	if err := os.WriteFile(filepath.Join(srcDir, "demo.go"), []byte(goBody), 0o644); err != nil {
		t.Fatal(err)
	}

	// Layer 3: SPEC frontmatter depends_on.
	specDir := filepath.Join(root, ".moai", "specs", "SPEC-GRAPH-TEST-001")
	if err := os.MkdirAll(specDir, 0o755); err != nil {
		t.Fatal(err)
	}
	specBody := `---
id: SPEC-GRAPH-TEST-001
title: "Fixture"
depends_on: [SPEC-GRAPH-DEP-A-001, SPEC-GRAPH-DEP-B-001]
---

# Body
`
	if err := os.WriteFile(filepath.Join(specDir, "spec.md"), []byte(specBody), 0o644); err != nil {
		t.Fatal(err)
	}

	return root
}

func TestBuild_AggregatesThreeLayers(t *testing.T) {
	root := fixtureProject(t)

	edges, err := Build(root)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	byKind := map[string][]Edge{}
	for _, e := range edges {
		byKind[e.Kind] = append(byKind[e.Kind], e)
	}

	// Layer 1 — import edges, canonicalized to full package paths via the
	// mermaid label table (short ids resolved, dotted arrow parsed, prose
	// outside the fence excluded).
	imports := byKind[KindImport]
	got := map[string]bool{}
	for _, e := range imports {
		got[e.Source+" -> "+e.Target] = true
	}
	wantImports := []string{
		"cmd/moai -> internal/cli",
		"internal/cli -> internal/config",
		"internal/cli -> internal/mx",
		"internal/mx -> internal/lsp",
		"internal/lsp -> internal/astgrep", // dotted -.-> arrow must parse
	}
	for _, w := range wantImports {
		if !got[w] {
			t.Errorf("missing import edge %q; got imports=%v", w, imports)
		}
	}
	for _, e := range imports {
		if strings.ContainsAny(e.Source, " *`") || strings.ContainsAny(e.Target, " *`") {
			t.Errorf("junk token in import edge: %+v", e)
		}
	}

	// Layer 2 — mx-spec edge with repo-relative source path and line number.
	mxSpecs := byKind[KindMXSpec]
	if len(mxSpecs) != 1 {
		t.Fatalf("want 1 mx-spec edge, got %d: %v", len(mxSpecs), mxSpecs)
	}
	e := mxSpecs[0]
	if e.Source != filepath.Join("internal", "demo", "demo.go") {
		t.Errorf("mx-spec source not repo-relative: %q", e.Source)
	}
	if e.Target != "SPEC-GRAPH-TEST-001" {
		t.Errorf("mx-spec target = %q", e.Target)
	}
	if e.Line != 3 { // 1-based line of the @MX tag that carries the SPEC sub-line
		t.Errorf("mx-spec line = %d, want 3", e.Line)
	}

	// Layer 3 — spec-depends edges from frontmatter.
	deps := byKind[KindSpecDepends]
	if len(deps) != 2 {
		t.Fatalf("want 2 spec-depends edges, got %d: %v", len(deps), deps)
	}
	gotDeps := map[string]bool{}
	for _, d := range deps {
		gotDeps[d.Source+" -> "+d.Target] = true
	}
	for _, w := range []string{
		"SPEC-GRAPH-TEST-001 -> SPEC-GRAPH-DEP-A-001",
		"SPEC-GRAPH-TEST-001 -> SPEC-GRAPH-DEP-B-001",
	} {
		if !gotDeps[w] {
			t.Errorf("missing spec-depends edge %q", w)
		}
	}
}

func TestBuild_MissingCodemapsArtifactFailOpen(t *testing.T) {
	root := t.TempDir()
	edges, err := Build(root)
	if err != nil {
		t.Fatalf("Build on empty project must fail open, got %v", err)
	}
	if len(edges) != 0 {
		t.Fatalf("want 0 edges on empty project, got %d", len(edges))
	}
}

func TestBuild_EdgesSortedDeterministically(t *testing.T) {
	root := fixtureProject(t)
	first, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	second, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(first) == 0 {
		t.Fatal("fixture produced no edges")
	}
	if !sort.SliceIsSorted(first, func(i, j int) bool { return edgeLess(first[i], first[j]) }) {
		t.Errorf("edges not sorted: %v", first)
	}
	if len(first) != len(second) {
		t.Fatalf("non-deterministic edge count: %d vs %d", len(first), len(second))
	}
	for i := range first {
		if first[i] != second[i] {
			t.Errorf("edge %d differs across runs: %+v vs %+v", i, first[i], second[i])
		}
	}
}

func TestWriteJSONL_OneEdgePerLine(t *testing.T) {
	root := fixtureProject(t)
	edges, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(root, "edges.jsonl")
	if err := WriteJSONL(out, edges); err != nil {
		t.Fatalf("WriteJSONL: %v", err)
	}

	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimRight(string(data), "\n"), "\n")
	if len(lines) != len(edges) {
		t.Fatalf("want %d lines, got %d", len(edges), len(lines))
	}
	for i, ln := range lines {
		var e Edge
		if err := json.Unmarshal([]byte(ln), &e); err != nil {
			t.Fatalf("line %d is not valid JSON: %v: %q", i, err, ln)
		}
		if e.Kind == "" || e.Source == "" || e.Target == "" {
			t.Fatalf("line %d missing required fields: %q", i, ln)
		}
	}

	// Byte-stable rewrite.
	if err := WriteJSONL(out, edges); err != nil {
		t.Fatal(err)
	}
	data2, _ := os.ReadFile(out)
	if string(data) != string(data2) {
		t.Error("WriteJSONL not byte-stable across runs")
	}
}

// edgeLess is the canonical edge ordering (kind, source, target, line).
func edgeLess(a, b Edge) bool {
	if a.Kind != b.Kind {
		return a.Kind < b.Kind
	}
	if a.Source != b.Source {
		return a.Source < b.Source
	}
	if a.Target != b.Target {
		return a.Target < b.Target
	}
	return a.Line < b.Line
}
