git_strategy:
    mode: manual
    provider: github
    github_username: ""
    gitlab:
        instance_url: ""
    manual:
        workflow: github-flow
        environment: local
        github_integration: false
        push_to_remote: false
        auto_checkpoint: disabled
        branch_prefix: ""
        main_branch: ""
        draft_pr: false
        required_reviews: 0
        branch_protection: false
        merge_method: squash
        automation:
            auto_branch: false
            auto_commit: true
            auto_pr: false
            auto_push: false
        branch_creation:
            auto_enabled: false
            prompt_always: true
        commit_style:
            format: conventional
            scope_required: false
        hooks:
            pre_commit: enforce
            pre_push: warn
            commit_msg: warn
    personal:
        workflow: github-flow
        environment: github
        github_integration: true
        push_to_remote: true
        auto_checkpoint: ""
        branch_prefix: feat/SPEC-
        main_branch: main
        draft_pr: false
        required_reviews: 0
        branch_protection: false
        merge_method: squash
        automation:
            auto_branch: true
            auto_commit: true
            auto_pr: true
            auto_push: true
        branch_creation:
            auto_enabled: true
            prompt_always: true
        commit_style:
            format: conventional
            scope_required: false
        hooks:
            pre_commit: enforce
            pre_push: enforce
            commit_msg: warn
    team:
        workflow: github-flow
        environment: github
        github_integration: true
        push_to_remote: true
        auto_checkpoint: ""
        branch_prefix: feat/SPEC-
        main_branch: main
        draft_pr: false
        required_reviews: 0
        branch_protection: true
        merge_method: squash
        automation:
            auto_branch: true
            auto_commit: true
            auto_pr: true
            auto_push: true
        branch_creation:
            auto_enabled: true
            prompt_always: true
        commit_style:
            format: conventional
            scope_required: true
        hooks:
            pre_commit: enforce
            pre_push: enforce
            commit_msg: warn
    auto_branch: false
    branch_prefix: moai/
    commit_style: conventional
    worktree_root: ""
    gitlab_instance_url: ""
