name: ci
on: [push]
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - extra: smoke
    steps:
      - run: "true"
