name: 🤖 AI Code Review & Auto-Approval

# AI-powered PR review with Claude or GPT-4
# Automatically reviews code quality, security, and testing
# Optionally auto-approves when quality threshold is met

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  ai-review:
    name: 🧠 AI Review with PR-Agent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🤖 AI Code Review
        uses: qodo-ai/pr-agent@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Choose LLM provider:
          # Option 1: Claude (Anthropic) - Recommended for MoAI
          openai_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-3-5-sonnet"

          # Option 2: GPT-4 (OpenAI)
          # openai_key: ${{ secrets.OPENAI_API_KEY }}
          # model: "gpt-4"

          # Review configuration
          pr_description: "Auto-generated review"
          review_pr_instructions: |
            Perform a comprehensive code review focusing on:
            - ✅ Code Quality (design patterns, readability, maintainability)
            - 🔒 Security (OWASP Top 10, vulnerability detection)
            - 🧪 Testing (test coverage, edge cases, fixtures)
            - 📚 Documentation (docstrings, comments, clarity)
            - 🎯 Performance (optimization opportunities, complexity)

            For Python projects, evaluate:
            - Type hints and mypy compliance
            - PEP-8 style and ruff linting
            - pytest coverage standards (85%+ target)
            - Async/await patterns
            - Exception handling

          # Auto-approval settings
          auto_approve: ${{ github.event.pull_request.draft == false }}
          approval_threshold: 0.80  # Approve if 80%+ quality

          # Comment settings
          comment_on_pr: true
          persistent_comment: true

      - name: 📊 Review Summary
        if: always()
        run: |
          echo "✅ AI Code Review Complete"
          echo "- Review comments posted on PR"
          echo "- Auto-approval: ${{ github.event.pull_request.draft == false }}"
          echo "- Threshold: 80% quality score"
