name: 📋 SPEC Issue Sync

on:
  pull_request:
    paths:
      - '.moai/specs/SPEC-*/spec.md'
    types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  sync-spec-to-issue:
    runs-on: ubuntu-latest
    name: 🔄 Sync SPEC to GitHub Issue

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Find and parse SPEC file
        id: spec
        run: |
          set -x  # Enable debug mode

          # Debug: Show current directory and files
          echo "=== Debug: Current directory ==="
          pwd
          ls -la

          echo "=== Debug: Looking for .moai/specs ==="
          ls -la .moai/ 2>&1 || echo ".moai/ directory not found"

          # Find SPEC files in the PR
          echo "=== Debug: Searching for SPEC files ==="
          find . -name "spec.md" -type f 2>&1 || echo "find command failed"

          spec_file=$(find .moai/specs -name "spec.md" -type f 2>&1 | head -1)
          echo "Found spec_file: [$spec_file]"

          if [ -z "$spec_file" ]; then
            echo "⚠️  No SPEC file found in .moai/specs"
            echo "Exiting gracefully (this is expected if no SPEC files changed)"
            exit 0
          fi

          echo "✅ Found SPEC file: $spec_file"
          echo "spec_file=$spec_file" >> $GITHUB_OUTPUT

          # Extract YAML metadata using grep
          spec_id=$(grep "^id:" "$spec_file" | sed 's/^id: *//' | tr -d ' "')
          spec_version=$(grep "^version:" "$spec_file" | sed 's/^version: *//' | tr -d ' "')
          spec_status=$(grep "^status:" "$spec_file" | sed 's/^status: *//' | tr -d ' "')
          spec_priority=$(grep "^priority:" "$spec_file" | sed 's/^priority: *//' | tr -d ' "')

          # Extract title from H1 heading
          spec_title=$(grep "^# @SPEC:" "$spec_file" | sed 's/^# @SPEC:[^:]*: //')

          echo "✅ Extracted SPEC metadata:"
          echo "  ID: $spec_id"
          echo "  Title: $spec_title"
          echo "  Version: $spec_version"
          echo "  Status: $spec_status"
          echo "  Priority: $spec_priority"

          echo "spec_id=$spec_id" >> $GITHUB_OUTPUT
          echo "spec_version=$spec_version" >> $GITHUB_OUTPUT
          echo "spec_status=$spec_status" >> $GITHUB_OUTPUT
          echo "spec_priority=$spec_priority" >> $GITHUB_OUTPUT
          echo "spec_title=$spec_title" >> $GITHUB_OUTPUT

      - name: Create GitHub Issue
        if: steps.spec.outputs.spec_id
        id: create-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spec_id="${{ steps.spec.outputs.spec_id }}"
          spec_version="${{ steps.spec.outputs.spec_version }}"
          spec_title="${{ steps.spec.outputs.spec_title }}"
          spec_status="${{ steps.spec.outputs.spec_status }}"
          spec_priority="${{ steps.spec.outputs.spec_priority }}"
          spec_file="${{ steps.spec.outputs.spec_file }}"

          # Read SPEC content (skip YAML frontmatter: 9 lines + 1 blank = 10 lines total)
          # Start reading from line 11
          spec_content=$(tail -n +11 "$spec_file")

          # Prepare issue body using heredoc (safer for special characters)
          cat > /tmp/issue_body_template.txt <<'ISSUE_BODY_EOF'
## SPEC Metadata

| Field | Value |
|-------|-------|
| **ID** | SPEC_ID_PLACEHOLDER |
| **Version** | SPEC_VERSION_PLACEHOLDER |
| **Status** | SPEC_STATUS_PLACEHOLDER |
| **Priority** | SPEC_PRIORITY_PLACEHOLDER |

## SPEC Document

SPEC_CONTENT_PLACEHOLDER

---

📎 **Branch**: `feature/SPEC_ID_PLACEHOLDER`
🔗 **PR**: #PR_NUMBER_PLACEHOLDER
📝 **Auto-synced**: This issue is automatically synchronized from the SPEC document
ISSUE_BODY_EOF

          # Replace placeholders
          sed -e "s/SPEC_ID_PLACEHOLDER/$spec_id/g" \
              -e "s/SPEC_VERSION_PLACEHOLDER/$spec_version/g" \
              -e "s/SPEC_STATUS_PLACEHOLDER/$spec_status/g" \
              -e "s/SPEC_PRIORITY_PLACEHOLDER/$spec_priority/g" \
              -e "s/PR_NUMBER_PLACEHOLDER/${{ github.event.pull_request.number }}/g" \
              /tmp/issue_body_template.txt > /tmp/issue_body_partial.txt

          # Insert SPEC content (handling it separately to preserve formatting)
          awk -v content="$spec_content" '{gsub(/SPEC_CONTENT_PLACEHOLDER/, content)}1' \
              /tmp/issue_body_partial.txt > /tmp/issue_body.txt

          echo "📋 Creating GitHub Issue..."
          echo "  Title: [SPEC-$spec_id] $spec_title (v$spec_version)"
          echo "  Body file: /tmp/issue_body.txt"
          wc -l /tmp/issue_body.txt

          # Create issue with labels using body-file
          issue_output=$(gh issue create \
            --title "[SPEC-$spec_id] $spec_title (v$spec_version)" \
            --body-file /tmp/issue_body.txt \
            --label "spec" \
            --label "planning" \
            --label "$spec_priority" 2>&1)

          echo "$issue_output" | tee /tmp/issue_output.txt

          # Extract issue number from output
          issue_num=$(echo "$issue_output" | grep -oE '/issues/[0-9]+' | grep -oE '[0-9]+' | head -1)

          if [ -z "$issue_num" ]; then
            echo "⚠️  Could not extract issue number from output"
            echo "Full output:"
            cat /tmp/issue_output.txt
            exit 1
          fi

          echo "issue_number=$issue_num" >> $GITHUB_OUTPUT
          echo "✅ Created issue #$issue_num"

      - name: Add PR comment
        if: steps.create-issue.outputs.issue_number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_num="${{ steps.create-issue.outputs.issue_number }}"
          spec_id="${{ steps.spec.outputs.spec_id }}"
          spec_title="${{ steps.spec.outputs.spec_title }}"

          pr_comment="✅ **SPEC GitHub Issue Created**

This SPEC has been synchronized to GitHub Issue.

📋 **Issue**: [#$issue_num - SPEC-$spec_id: $spec_title](../issues/$issue_num)
🔗 **SPEC File**: \`.moai/specs/SPEC-$spec_id/spec.md\`

The issue will be automatically updated as you modify the SPEC document."

          gh pr comment ${{ github.event.pull_request.number }} --body "$pr_comment"
          echo "✅ Added PR comment linking to issue #$issue_num"
