name: Release & Deploy to PyPI

# 트리거: GitHub Release가 published 상태로 생성되었을 때
on:
  release:
    types: [published]

jobs:
  deploy:
    name: 📦 Deploy to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: 🔨 Build package
        run: |
          echo "🏗️  Building package..."
          uv build
          echo "✅ Package built successfully"
          ls -lh dist/

      - name: 🚀 Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "📤 Publishing to PyPI..."
          uv publish --publish-url https://upload.pypi.org/legacy/
          echo "✅ Package published successfully"

      - name: ✨ Deployment complete
        run: |
          echo "🎉 Release deployment complete!"
          echo ""
          echo "📦 Package: moai-adk"
          echo "🏷️  Release: ${{ github.event.release.tag_name }}"
          echo "🔗 PyPI: https://pypi.org/project/moai-adk/${{ github.event.release.tag_name }}/"
