//go:build integration

// Package pipeline: integration tests for Path B1 (Figma extractor meta-harness stub).
// SPEC-V3R3-DESIGN-PIPELINE-001 Phase 4 (T4-03).
//
// Because real meta-harness skill files live in the user space, the tests
// create a stub SKILL.md inside t.TempDir() to verify the contract.
// The real .claude/skills/ directory is never polluted.
package pipeline

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/modu-ai/moai-adk/internal/design/dtcg"
)

// writeStubFigmaExtractorSkill creates a harness-figma-extractor/SKILL.md stub.
// Simulates the frontmatter contract for files produced by meta-harness.
func writeStubFigmaExtractorSkill(t *testing.T, skillsDir string) string {
	t.Helper()

	skillDir := filepath.Join(skillsDir, "harness-figma-extractor")
	if err := os.MkdirAll(skillDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// REQ-DPL-002: must include Figma file ID + page selectors + credential reference.
	skillContent := `---
name: harness-figma-extractor
description: Figma 디자인 추출기 — 프로젝트 전용 meta-harness 생성 스킬
figma_file_id: "ABCDEF1234567890"
figma_page_selectors:
  - "Design System"
  - "Components"
figma_credential_ref: "env:FIGMA_TOKEN"
generated_by: moai-meta-harness
spec_id: SPEC-V3R3-DESIGN-PIPELINE-001
---

# Figma 추출기 (프로젝트 전용)

이 스킬은 meta-harness가 생성한 Figma 전용 디자인 추출기입니다.
`

	skillPath := filepath.Join(skillDir, "SKILL.md")
	if err := os.WriteFile(skillPath, []byte(skillContent), 0o644); err != nil {
		t.Fatal(err)
	}

	return skillPath
}

// parseFrontmatter parses YAML frontmatter (--- ... ---) into key-value pairs.
// Only simple key: value form is supported; YAML arrays are handled separately.
func parseFrontmatter(t *testing.T, content string) map[string]string {
	t.Helper()

	result := make(map[string]string)
	inFrontmatter := false
	scanner := bufio.NewScanner(strings.NewReader(content))

	lineCount := 0
	for scanner.Scan() {
		line := scanner.Text()
		if line == "---" {
			lineCount++
			if lineCount == 1 {
				inFrontmatter = true
				continue
			}
			if lineCount == 2 {
				break
			}
		}
		if !inFrontmatter {
			continue
		}

		// Simple key: value parsing (strip surrounding quotes).
		idx := strings.Index(line, ":")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		val = strings.Trim(val, `"'`)
		result[key] = val
	}

	return result
}

// TestPathB1_FigmaExtractorSkillFrontmatter verifies the stub SKILL.md frontmatter.
// REQ-DPL-002: confirms inclusion of Figma file ID, page selectors, credential reference.
func TestPathB1_FigmaExtractorSkillFrontmatter(t *testing.T) {
	skillsDir := t.TempDir()
	skillPath := writeStubFigmaExtractorSkill(t, skillsDir)

	data, err := os.ReadFile(skillPath)
	if err != nil {
		t.Fatalf("SKILL.md 읽기 실패: %v", err)
	}

	content := string(data)
	fm := parseFrontmatter(t, content)

	// figma_file_id must exist and be non-empty.
	if fm["figma_file_id"] == "" {
		t.Error("frontmatter에 figma_file_id 없음")
	}

	// figma_credential_ref must exist.
	if fm["figma_credential_ref"] == "" {
		t.Error("frontmatter에 figma_credential_ref 없음")
	}

	// figma_page_selectors must exist (verified via content substring).
	if !strings.Contains(content, "figma_page_selectors") {
		t.Error("SKILL.md에 figma_page_selectors 없음")
	}

	t.Logf("figma_file_id: %s", fm["figma_file_id"])
	t.Logf("figma_credential_ref: %s", fm["figma_credential_ref"])
}

// TestPathB1_GeneratedTokensValidate: tokens.json generated by Path B1 must pass DTCG 2025.10 validation.
func TestPathB1_GeneratedTokensValidate(t *testing.T) {
	// Simulate tokens.json produced by the meta-harness figma-extractor.
	simulatedFigmaTokens := map[string]any{
		"color-primary": map[string]any{
			"$type":  "color",
			"$value": "#0F172A",
		},
		"color-accent": map[string]any{
			"$type":  "color",
			"$value": "#6366F1",
		},
		"font-heading": map[string]any{
			"$type":  "fontFamily",
			"$value": []any{"Geist", "sans-serif"},
		},
		"space-base": map[string]any{
			"$type":  "dimension",
			"$value": "4px",
		},
	}

	report, err := dtcg.Validate(simulatedFigmaTokens)
	if err != nil {
		t.Fatalf("Validate() 실행 실패: %v", err)
	}

	if !report.Valid {
		t.Errorf("Path B1 토큰이 DTCG 검증 실패. 오류 %d개:", len(report.Errors))
		for _, e := range report.Errors {
			t.Logf("  - %s", e.Error())
		}
	}

	t.Logf("Path B1 토큰 %d개 검증 통과", report.TokenCount)
}

// TestPathB1_PathSelectionRecordsB1: "B1" recorded in path-selection.json.
func TestPathB1_PathSelectionRecordsB1(t *testing.T) {
	dir := t.TempDir()

	ps := PathSelection{
		Path:               "B1",
		BrandContextLoaded: true,
		SpecID:             "SPEC-V3R3-TEST-B1",
		Timestamp:          time.Date(2026, 4, 27, 0, 0, 0, 0, time.UTC),
		SessionID:          "test-session-b1",
	}

	if err := WritePathSelection(dir, ps); err != nil {
		t.Fatalf("WritePathSelection 실패: %v", err)
	}

	got, err := ReadPathSelection(dir)
	if err != nil {
		t.Fatalf("ReadPathSelection 실패: %v", err)
	}

	if got.Path != "B1" {
		t.Errorf("Path = %q, want 'B1'", got.Path)
	}
	if !got.BrandContextLoaded {
		t.Error("BrandContextLoaded = false, want true")
	}
}
