//go:build integration

// Package pipeline: integration tests for Path B2 (Pencil MCP meta-harness stub).
// SPEC-V3R3-DESIGN-PIPELINE-001 Phase 4 (T4-04).
//
// Verification:
// 1. harness-pencil-mcp/SKILL.md stub frontmatter (.pen paths + MCP endpoint).
// 2. The generated tokens.json passes DTCG validation.
// 3. "B2" is recorded in path-selection.json.
// 4. No reference to moai-workflow-pencil-integration (the file is removed in Phase 5 T5-03).
//
// [HARD] stub files live only inside t.TempDir() — the real .claude/skills/ must never be polluted.
package pipeline

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/modu-ai/moai-adk/internal/design/dtcg"
)

// writeStubPencilMCPSkill creates a harness-pencil-mcp/SKILL.md stub.
// REQ-DPL-003: includes .pen file paths + Pencil MCP server endpoint.
func writeStubPencilMCPSkill(t *testing.T, skillsDir string) string {
	t.Helper()

	skillDir := filepath.Join(skillsDir, "harness-pencil-mcp")
	if err := os.MkdirAll(skillDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// REQ-DPL-003: must include .pen file paths + MCP server endpoint.
	skillContent := `---
name: harness-pencil-mcp
description: Pencil MCP 통합 스킬 — 프로젝트 전용 meta-harness 생성 스킬
pen_file_paths:
  - "designs/main.pen"
  - "designs/components.pen"
pencil_mcp_endpoint: "http://localhost:5100"
generated_by: moai-meta-harness
spec_id: SPEC-V3R3-DESIGN-PIPELINE-001
---

# Pencil MCP 통합 (프로젝트 전용)

이 스킬은 meta-harness가 생성한 Pencil MCP 전용 스킬입니다.
moai-workflow-pencil-integration을 대체합니다.
`

	skillPath := filepath.Join(skillDir, "SKILL.md")
	if err := os.WriteFile(skillPath, []byte(skillContent), 0o644); err != nil {
		t.Fatal(err)
	}

	return skillPath
}

// TestPathB2_PencilMCPSkillFrontmatter verifies stub SKILL.md frontmatter.
// REQ-DPL-003: confirms inclusion of .pen file paths + Pencil MCP server endpoint.
func TestPathB2_PencilMCPSkillFrontmatter(t *testing.T) {
	skillsDir := t.TempDir()
	skillPath := writeStubPencilMCPSkill(t, skillsDir)

	data, err := os.ReadFile(skillPath)
	if err != nil {
		t.Fatalf("SKILL.md 읽기 실패: %v", err)
	}

	content := string(data)
	fm := parseFrontmatter(t, content)

	// pencil_mcp_endpoint must exist and be non-empty.
	if fm["pencil_mcp_endpoint"] == "" {
		t.Error("frontmatter에 pencil_mcp_endpoint 없음")
	}

	// pen_file_paths must exist.
	if !strings.Contains(content, "pen_file_paths") {
		t.Error("SKILL.md에 pen_file_paths 없음")
	}

	// Verify a .pen file reference is present.
	if !strings.Contains(content, ".pen") {
		t.Error("SKILL.md에 .pen 파일 참조 없음")
	}

	t.Logf("pencil_mcp_endpoint: %s", fm["pencil_mcp_endpoint"])
}

// TestPathB2_GeneratedTokensValidate: tokens.json generated by Path B2 must pass DTCG 2025.10 validation.
func TestPathB2_GeneratedTokensValidate(t *testing.T) {
	// Simulate tokens.json produced by Pencil MCP.
	simulatedPencilTokens := map[string]any{
		"color-surface": map[string]any{
			"$type":  "color",
			"$value": "#FFFFFF",
		},
		"color-text": map[string]any{
			"$type":  "color",
			"$value": "#111827",
		},
		"border-radius-sm": map[string]any{
			"$type":  "dimension",
			"$value": "4px",
		},
		"border-radius-md": map[string]any{
			"$type":  "dimension",
			"$value": "8px",
		},
		"font-weight-bold": map[string]any{
			"$type":  "fontWeight",
			"$value": 700.0,
		},
	}

	report, err := dtcg.Validate(simulatedPencilTokens)
	if err != nil {
		t.Fatalf("Validate() 실행 실패: %v", err)
	}

	if !report.Valid {
		t.Errorf("Path B2 토큰이 DTCG 검증 실패. 오류 %d개:", len(report.Errors))
		for _, e := range report.Errors {
			t.Logf("  - %s", e.Error())
		}
	}

	t.Logf("Path B2 토큰 %d개 검증 통과", report.TokenCount)
}

// TestPathB2_PathSelectionRecordsB2: "B2" recorded in path-selection.json.
func TestPathB2_PathSelectionRecordsB2(t *testing.T) {
	dir := t.TempDir()

	ps := PathSelection{
		Path:               "B2",
		BrandContextLoaded: false,
		SpecID:             "SPEC-V3R3-TEST-B2",
		Timestamp:          time.Date(2026, 4, 27, 0, 0, 0, 0, time.UTC),
		SessionID:          "test-session-b2",
	}

	if err := WritePathSelection(dir, ps); err != nil {
		t.Fatalf("WritePathSelection 실패: %v", err)
	}

	got, err := ReadPathSelection(dir)
	if err != nil {
		t.Fatalf("ReadPathSelection 실패: %v", err)
	}

	if got.Path != "B2" {
		t.Errorf("Path = %q, want 'B2'", got.Path)
	}
}

// TestPathB2_LegacyPencilIntegrationAbsent verifies absence of moai-workflow-pencil-integration references.
// [HARD] Real removal happens in Phase 5 T5-03. This test verifies absence at the stub level.
func TestPathB2_LegacyPencilIntegrationAbsent(t *testing.T) {
	skillsDir := t.TempDir()

	// The stub environment never creates the legacy skill — verify absence.
	legacyPath := filepath.Join(skillsDir, "moai-workflow-pencil-integration", "SKILL.md")

	_, err := os.Stat(legacyPath)
	if !os.IsNotExist(err) {
		t.Errorf("레거시 moai-workflow-pencil-integration이 stub 환경에 존재함 — 없어야 함")
	}

	// Only the Path B2 stub must exist.
	writeStubPencilMCPSkill(t, skillsDir)
	pencilMCPPath := filepath.Join(skillsDir, "harness-pencil-mcp", "SKILL.md")
	if _, err := os.Stat(pencilMCPPath); os.IsNotExist(err) {
		t.Error("harness-pencil-mcp/SKILL.md stub이 없음")
	}

	t.Log("검증 완료: stub 환경에 moai-workflow-pencil-integration 없음, harness-pencil-mcp 존재")
}
