// catalog_loader.go — typed loader for internal/template/catalog.yaml.
//
// LoadCatalog reads catalog.yaml from the given fs.FS, unmarshals it into a
// strongly-typed Catalog struct, and returns it. The caller is responsible for
// providing the correct FS; in production callers pass embeddedRaw (the raw
// embed.FS before the "templates/" prefix strip), because catalog.yaml lives at
// the embed root, not inside templates/.
//
// SPEC-V3R4-CATALOG-001 T-019, T-020, T-021
package template

import (
	"fmt"
	"io/fs"

	"gopkg.in/yaml.v3"
)

// Tier constants — centralized per CLAUDE.local.md §14 no-hardcoding rule.
// All tier strings used in catalog.yaml MUST derive from these constants.
const (
	// TierCore identifies a component that is always installed by "moai init".
	TierCore = "core"

	// TierHarnessGenerated identifies components that are generated by the
	// builder-harness workflow and are not part of the static template set.
	TierHarnessGenerated = "harness-generated"

	// TierOptionalPackPrefix is the prefix for pack-scoped tiers.
	// A full optional-pack tier string takes the form:
	//   optional-pack:<packName>
	// Use FormatOptionalPackTier to construct valid values.
	TierOptionalPackPrefix = "optional-pack:"
)

// FormatOptionalPackTier returns the canonical tier string for an optional pack.
// Example: FormatOptionalPackTier("backend") → "optional-pack:backend"
func FormatOptionalPackTier(packName string) string {
	return TierOptionalPackPrefix + packName
}

// Entry represents a single skill or agent in catalog.yaml.
//
// Fields:
//   - Name: unique identifier (matches directory or file basename without extension)
//   - Tier: one of TierCore, TierHarnessGenerated, or FormatOptionalPackTier(<packName>)
//   - Path: path relative to the templates/ root (e.g. "templates/.claude/skills/moai/")
//   - Hash: sha256 hex digest of the normalized source file (64 lowercase hex chars)
//   - Version: semver string (e.g. "1.0.0")
type Entry struct {
	Name    string `yaml:"name"`
	Tier    string `yaml:"tier"`
	Path    string `yaml:"path"`
	Hash    string `yaml:"hash"`
	Version string `yaml:"version"`
}

// Pack represents an optional-pack section in catalog.yaml.
// Each pack has a human-readable description, an optional dependency list
// (other pack names), and lists of skills and agents it provides.
type Pack struct {
	Description string  `yaml:"description"`
	DependsOn   []string `yaml:"depends_on"`
	Skills      []Entry  `yaml:"skills"`
	Agents      []Entry  `yaml:"agents"`

	// Reserved optional marketplace fields (REQ-024).
	// These are interface{} to detect non-string values in TestCatalogReservedFieldType.
	MarketplaceID  interface{} `yaml:"marketplace_id,omitempty"`
	MarketplaceURL interface{} `yaml:"marketplace_url,omitempty"`
	Publisher      interface{} `yaml:"publisher,omitempty"`
}

// TierSection holds the skills and agents for a flat (non-pack) tier section
// such as catalog.core or catalog.harness_generated.
type TierSection struct {
	Skills []Entry `yaml:"skills"`
	Agents []Entry `yaml:"agents"`
}

// CatalogSections is the top-level catalog container.
type CatalogSections struct {
	Core             TierSection        `yaml:"core"`
	OptionalPacks    map[string]*Pack   `yaml:"optional_packs"`
	HarnessGenerated TierSection        `yaml:"harness_generated"`
}

// Catalog is the root document type for catalog.yaml.
//
// Usage:
//
//	cat, err := LoadCatalog(embeddedRaw)
//	if err != nil { ... }
//	entry, ok := cat.LookupSkill("expert-backend")
type Catalog struct {
	Version     string          `yaml:"version"`
	GeneratedAt string          `yaml:"generated_at"`
	Catalog     CatalogSections `yaml:"catalog"`
}

// LoadCatalog reads "catalog.yaml" from the provided fs.FS and unmarshals it
// into a *Catalog.
//
// The FS MUST expose "catalog.yaml" at its root. In practice, pass embeddedRaw
// (the raw embed.FS, not the EmbeddedTemplates() sub-FS which strips the
// "templates/" prefix) because catalog.yaml is a sibling of templates/, not
// inside it.
//
// Returns an error if catalog.yaml is absent or malformed.
//
// @MX:ANCHOR: [AUTO] Primary entry point for catalog.yaml access — expected fan_in >= 3 (audit suite, deployer, follow-up SPEC loaders)
// @MX:REASON: [AUTO] fan_in >= 3; sole typed parsing path for catalog.yaml; downstream SPECs SPEC-V3R4-CATALOG-002..007 all route through this function
func LoadCatalog(fsys fs.FS) (*Catalog, error) {
	data, err := fs.ReadFile(fsys, "catalog.yaml")
	if err != nil {
		return nil, fmt.Errorf("CATALOG_MANIFEST_ABSENT: catalog.yaml not found in FS: %w", err)
	}

	var cat Catalog
	if err := yaml.Unmarshal(data, &cat); err != nil {
		return nil, fmt.Errorf("catalog.yaml parse error: %w", err)
	}

	return &cat, nil
}

// AllEntries returns a flat slice of every entry (skill and agent) across all
// tier sections in declaration order: core.skills, core.agents,
// optional_packs.*.skills, optional_packs.*.agents, harness_generated.skills,
// harness_generated.agents.
//
// This is used by audit tests and lookup helpers that need the full population.
func (c *Catalog) AllEntries() []Entry {
	var entries []Entry
	entries = append(entries, c.Catalog.Core.Skills...)
	entries = append(entries, c.Catalog.Core.Agents...)
	for _, pack := range c.Catalog.OptionalPacks {
		entries = append(entries, pack.Skills...)
		entries = append(entries, pack.Agents...)
	}
	entries = append(entries, c.Catalog.HarnessGenerated.Skills...)
	entries = append(entries, c.Catalog.HarnessGenerated.Agents...)
	return entries
}

// LookupSkill searches all tier sections for the first skill entry with the
// given name and returns a pointer to it along with a boolean ok indicator.
//
// The returned *Entry points into the Catalog's internal slice — callers
// MUST NOT modify it.
func (c *Catalog) LookupSkill(name string) (*Entry, bool) {
	for i := range c.Catalog.Core.Skills {
		if c.Catalog.Core.Skills[i].Name == name {
			return &c.Catalog.Core.Skills[i], true
		}
	}
	for _, pack := range c.Catalog.OptionalPacks {
		for i := range pack.Skills {
			if pack.Skills[i].Name == name {
				return &pack.Skills[i], true
			}
		}
	}
	for i := range c.Catalog.HarnessGenerated.Skills {
		if c.Catalog.HarnessGenerated.Skills[i].Name == name {
			return &c.Catalog.HarnessGenerated.Skills[i], true
		}
	}
	return nil, false
}

// LookupAgent searches all tier sections for the first agent entry with the
// given name and returns a pointer to it along with a boolean ok indicator.
//
// The returned *Entry points into the Catalog's internal slice — callers
// MUST NOT modify it.
func (c *Catalog) LookupAgent(name string) (*Entry, bool) {
	for i := range c.Catalog.Core.Agents {
		if c.Catalog.Core.Agents[i].Name == name {
			return &c.Catalog.Core.Agents[i], true
		}
	}
	for _, pack := range c.Catalog.OptionalPacks {
		for i := range pack.Agents {
			if pack.Agents[i].Name == name {
				return &pack.Agents[i], true
			}
		}
	}
	for i := range c.Catalog.HarnessGenerated.Agents {
		if c.Catalog.HarnessGenerated.Agents[i].Name == name {
			return &c.Catalog.HarnessGenerated.Agents[i], true
		}
	}
	return nil, false
}
